/*
 * Copyright Octelium Labs, LLC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: rcordiumv1.proto

package rcordiumv1

import (
	context "context"
	cordiumv1 "github.com/octelium/octelium/apis/main/cordiumv1"
	rmetav1 "github.com/octelium/octelium/apis/rsc/rmetav1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_CreateWorkspace_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/CreateWorkspace"
	ResourceService_UpdateWorkspace_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateWorkspace"
	ResourceService_GetWorkspace_FullMethodName        = "/octelium.api.rsc.cordium.v1.ResourceService/GetWorkspace"
	ResourceService_ListWorkspace_FullMethodName       = "/octelium.api.rsc.cordium.v1.ResourceService/ListWorkspace"
	ResourceService_DeleteWorkspace_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteWorkspace"
	ResourceService_WatchWorkspace_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/WatchWorkspace"
	ResourceService_CreateSecret_FullMethodName        = "/octelium.api.rsc.cordium.v1.ResourceService/CreateSecret"
	ResourceService_UpdatSecret_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/UpdatSecret"
	ResourceService_GetSecret_FullMethodName           = "/octelium.api.rsc.cordium.v1.ResourceService/GetSecret"
	ResourceService_ListSecret_FullMethodName          = "/octelium.api.rsc.cordium.v1.ResourceService/ListSecret"
	ResourceService_DeleteSecret_FullMethodName        = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteSecret"
	ResourceService_WatchSecret_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/WatchSecret"
	ResourceService_CreateTemplate_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/CreateTemplate"
	ResourceService_UpdateTemplate_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateTemplate"
	ResourceService_GetTemplate_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/GetTemplate"
	ResourceService_ListTemplate_FullMethodName        = "/octelium.api.rsc.cordium.v1.ResourceService/ListTemplate"
	ResourceService_DeleteTemplate_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteTemplate"
	ResourceService_WatchTemplate_FullMethodName       = "/octelium.api.rsc.cordium.v1.ResourceService/WatchTemplate"
	ResourceService_CreateSpace_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/CreateSpace"
	ResourceService_UpdateSpace_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateSpace"
	ResourceService_GetSpace_FullMethodName            = "/octelium.api.rsc.cordium.v1.ResourceService/GetSpace"
	ResourceService_ListSpace_FullMethodName           = "/octelium.api.rsc.cordium.v1.ResourceService/ListSpace"
	ResourceService_DeleteSpace_FullMethodName         = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteSpace"
	ResourceService_WatchSpace_FullMethodName          = "/octelium.api.rsc.cordium.v1.ResourceService/WatchSpace"
	ResourceService_CreateMembership_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/CreateMembership"
	ResourceService_UpdateMembership_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateMembership"
	ResourceService_GetMembership_FullMethodName       = "/octelium.api.rsc.cordium.v1.ResourceService/GetMembership"
	ResourceService_ListMembership_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/ListMembership"
	ResourceService_DeleteMembership_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteMembership"
	ResourceService_CreateGitProvider_FullMethodName   = "/octelium.api.rsc.cordium.v1.ResourceService/CreateGitProvider"
	ResourceService_UpdateGitProvider_FullMethodName   = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateGitProvider"
	ResourceService_GetGitProvider_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/GetGitProvider"
	ResourceService_ListGitProvider_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/ListGitProvider"
	ResourceService_DeleteGitProvider_FullMethodName   = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteGitProvider"
	ResourceService_WatchGitProvider_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/WatchGitProvider"
	ResourceService_CreateUserSecret_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/CreateUserSecret"
	ResourceService_UpdateUserSecret_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateUserSecret"
	ResourceService_GetUserSecret_FullMethodName       = "/octelium.api.rsc.cordium.v1.ResourceService/GetUserSecret"
	ResourceService_ListUserSecret_FullMethodName      = "/octelium.api.rsc.cordium.v1.ResourceService/ListUserSecret"
	ResourceService_DeleteUserSecret_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteUserSecret"
	ResourceService_WatchUserSecret_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/WatchUserSecret"
	ResourceService_CreateUserConfig_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/CreateUserConfig"
	ResourceService_UpdateUserConfig_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateUserConfig"
	ResourceService_GetUserConfig_FullMethodName       = "/octelium.api.rsc.cordium.v1.ResourceService/GetUserConfig"
	ResourceService_DeleteUserConfig_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/DeleteUserConfig"
	ResourceService_WatchUserConfig_FullMethodName     = "/octelium.api.rsc.cordium.v1.ResourceService/WatchUserConfig"
	ResourceService_GetClusterConfig_FullMethodName    = "/octelium.api.rsc.cordium.v1.ResourceService/GetClusterConfig"
	ResourceService_UpdateClusterConfig_FullMethodName = "/octelium.api.rsc.cordium.v1.ResourceService/UpdateClusterConfig"
	ResourceService_WatchClusterConfig_FullMethodName  = "/octelium.api.rsc.cordium.v1.ResourceService/WatchClusterConfig"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	CreateWorkspace(ctx context.Context, in *cordiumv1.Workspace, opts ...grpc.CallOption) (*cordiumv1.Workspace, error)
	UpdateWorkspace(ctx context.Context, in *cordiumv1.Workspace, opts ...grpc.CallOption) (*cordiumv1.Workspace, error)
	GetWorkspace(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Workspace, error)
	ListWorkspace(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.WorkspaceList, error)
	DeleteWorkspace(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchWorkspace(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateSecret(ctx context.Context, in *cordiumv1.Secret, opts ...grpc.CallOption) (*cordiumv1.Secret, error)
	UpdatSecret(ctx context.Context, in *cordiumv1.Secret, opts ...grpc.CallOption) (*cordiumv1.Secret, error)
	GetSecret(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Secret, error)
	ListSecret(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.SecretList, error)
	DeleteSecret(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchSecret(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateTemplate(ctx context.Context, in *cordiumv1.Template, opts ...grpc.CallOption) (*cordiumv1.Template, error)
	UpdateTemplate(ctx context.Context, in *cordiumv1.Template, opts ...grpc.CallOption) (*cordiumv1.Template, error)
	GetTemplate(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Template, error)
	ListTemplate(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.TemplateList, error)
	DeleteTemplate(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchTemplate(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateSpace(ctx context.Context, in *cordiumv1.Space, opts ...grpc.CallOption) (*cordiumv1.Space, error)
	UpdateSpace(ctx context.Context, in *cordiumv1.Space, opts ...grpc.CallOption) (*cordiumv1.Space, error)
	GetSpace(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Space, error)
	ListSpace(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.SpaceList, error)
	DeleteSpace(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchSpace(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateMembership(ctx context.Context, in *cordiumv1.Membership, opts ...grpc.CallOption) (*cordiumv1.Membership, error)
	UpdateMembership(ctx context.Context, in *cordiumv1.Membership, opts ...grpc.CallOption) (*cordiumv1.Membership, error)
	GetMembership(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Membership, error)
	ListMembership(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.MembershipList, error)
	DeleteMembership(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	CreateGitProvider(ctx context.Context, in *cordiumv1.GitProvider, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error)
	UpdateGitProvider(ctx context.Context, in *cordiumv1.GitProvider, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error)
	GetGitProvider(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error)
	ListGitProvider(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.GitProviderList, error)
	DeleteGitProvider(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchGitProvider(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateUserSecret(ctx context.Context, in *cordiumv1.UserSecret, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error)
	UpdateUserSecret(ctx context.Context, in *cordiumv1.UserSecret, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error)
	GetUserSecret(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error)
	ListUserSecret(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.UserSecretList, error)
	DeleteUserSecret(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchUserSecret(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	CreateUserConfig(ctx context.Context, in *cordiumv1.UserConfig, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error)
	UpdateUserConfig(ctx context.Context, in *cordiumv1.UserConfig, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error)
	GetUserConfig(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error)
	DeleteUserConfig(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error)
	WatchUserConfig(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
	GetClusterConfig(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.ClusterConfig, error)
	UpdateClusterConfig(ctx context.Context, in *cordiumv1.ClusterConfig, opts ...grpc.CallOption) (*cordiumv1.ClusterConfig, error)
	WatchClusterConfig(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) CreateWorkspace(ctx context.Context, in *cordiumv1.Workspace, opts ...grpc.CallOption) (*cordiumv1.Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Workspace)
	err := c.cc.Invoke(ctx, ResourceService_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateWorkspace(ctx context.Context, in *cordiumv1.Workspace, opts ...grpc.CallOption) (*cordiumv1.Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Workspace)
	err := c.cc.Invoke(ctx, ResourceService_UpdateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetWorkspace(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Workspace)
	err := c.cc.Invoke(ctx, ResourceService_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListWorkspace(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.WorkspaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.WorkspaceList)
	err := c.cc.Invoke(ctx, ResourceService_ListWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteWorkspace(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchWorkspace(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[0], ResourceService_WatchWorkspace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchWorkspaceClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateSecret(ctx context.Context, in *cordiumv1.Secret, opts ...grpc.CallOption) (*cordiumv1.Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Secret)
	err := c.cc.Invoke(ctx, ResourceService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdatSecret(ctx context.Context, in *cordiumv1.Secret, opts ...grpc.CallOption) (*cordiumv1.Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Secret)
	err := c.cc.Invoke(ctx, ResourceService_UpdatSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetSecret(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Secret)
	err := c.cc.Invoke(ctx, ResourceService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListSecret(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.SecretList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.SecretList)
	err := c.cc.Invoke(ctx, ResourceService_ListSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteSecret(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchSecret(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[1], ResourceService_WatchSecret_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchSecretClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateTemplate(ctx context.Context, in *cordiumv1.Template, opts ...grpc.CallOption) (*cordiumv1.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Template)
	err := c.cc.Invoke(ctx, ResourceService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateTemplate(ctx context.Context, in *cordiumv1.Template, opts ...grpc.CallOption) (*cordiumv1.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Template)
	err := c.cc.Invoke(ctx, ResourceService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetTemplate(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Template)
	err := c.cc.Invoke(ctx, ResourceService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListTemplate(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.TemplateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.TemplateList)
	err := c.cc.Invoke(ctx, ResourceService_ListTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteTemplate(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchTemplate(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[2], ResourceService_WatchTemplate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchTemplateClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateSpace(ctx context.Context, in *cordiumv1.Space, opts ...grpc.CallOption) (*cordiumv1.Space, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Space)
	err := c.cc.Invoke(ctx, ResourceService_CreateSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateSpace(ctx context.Context, in *cordiumv1.Space, opts ...grpc.CallOption) (*cordiumv1.Space, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Space)
	err := c.cc.Invoke(ctx, ResourceService_UpdateSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetSpace(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Space, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Space)
	err := c.cc.Invoke(ctx, ResourceService_GetSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListSpace(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.SpaceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.SpaceList)
	err := c.cc.Invoke(ctx, ResourceService_ListSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteSpace(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchSpace(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[3], ResourceService_WatchSpace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchSpaceClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateMembership(ctx context.Context, in *cordiumv1.Membership, opts ...grpc.CallOption) (*cordiumv1.Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Membership)
	err := c.cc.Invoke(ctx, ResourceService_CreateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateMembership(ctx context.Context, in *cordiumv1.Membership, opts ...grpc.CallOption) (*cordiumv1.Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Membership)
	err := c.cc.Invoke(ctx, ResourceService_UpdateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetMembership(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.Membership)
	err := c.cc.Invoke(ctx, ResourceService_GetMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListMembership(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.MembershipList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.MembershipList)
	err := c.cc.Invoke(ctx, ResourceService_ListMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteMembership(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) CreateGitProvider(ctx context.Context, in *cordiumv1.GitProvider, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.GitProvider)
	err := c.cc.Invoke(ctx, ResourceService_CreateGitProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateGitProvider(ctx context.Context, in *cordiumv1.GitProvider, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.GitProvider)
	err := c.cc.Invoke(ctx, ResourceService_UpdateGitProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetGitProvider(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.GitProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.GitProvider)
	err := c.cc.Invoke(ctx, ResourceService_GetGitProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListGitProvider(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.GitProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.GitProviderList)
	err := c.cc.Invoke(ctx, ResourceService_ListGitProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteGitProvider(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteGitProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchGitProvider(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[4], ResourceService_WatchGitProvider_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchGitProviderClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateUserSecret(ctx context.Context, in *cordiumv1.UserSecret, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserSecret)
	err := c.cc.Invoke(ctx, ResourceService_CreateUserSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateUserSecret(ctx context.Context, in *cordiumv1.UserSecret, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserSecret)
	err := c.cc.Invoke(ctx, ResourceService_UpdateUserSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetUserSecret(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.UserSecret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserSecret)
	err := c.cc.Invoke(ctx, ResourceService_GetUserSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListUserSecret(ctx context.Context, in *rmetav1.ListOptions, opts ...grpc.CallOption) (*cordiumv1.UserSecretList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserSecretList)
	err := c.cc.Invoke(ctx, ResourceService_ListUserSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteUserSecret(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteUserSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchUserSecret(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[5], ResourceService_WatchUserSecret_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchUserSecretClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) CreateUserConfig(ctx context.Context, in *cordiumv1.UserConfig, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserConfig)
	err := c.cc.Invoke(ctx, ResourceService_CreateUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateUserConfig(ctx context.Context, in *cordiumv1.UserConfig, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserConfig)
	err := c.cc.Invoke(ctx, ResourceService_UpdateUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetUserConfig(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.UserConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.UserConfig)
	err := c.cc.Invoke(ctx, ResourceService_GetUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) DeleteUserConfig(ctx context.Context, in *rmetav1.DeleteOptions, opts ...grpc.CallOption) (*rmetav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(rmetav1.OperationResult)
	err := c.cc.Invoke(ctx, ResourceService_DeleteUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchUserConfig(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[6], ResourceService_WatchUserConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchUserConfigClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

func (c *resourceServiceClient) GetClusterConfig(ctx context.Context, in *rmetav1.GetOptions, opts ...grpc.CallOption) (*cordiumv1.ClusterConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.ClusterConfig)
	err := c.cc.Invoke(ctx, ResourceService_GetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) UpdateClusterConfig(ctx context.Context, in *cordiumv1.ClusterConfig, opts ...grpc.CallOption) (*cordiumv1.ClusterConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cordiumv1.ClusterConfig)
	err := c.cc.Invoke(ctx, ResourceService_UpdateClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) WatchClusterConfig(ctx context.Context, in *rmetav1.WatchOptions, opts ...grpc.CallOption) (grpc.ServerStreamingClient[rmetav1.WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[7], ResourceService_WatchClusterConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchClusterConfigClient = grpc.ServerStreamingClient[rmetav1.WatchEvent]

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
type ResourceServiceServer interface {
	CreateWorkspace(context.Context, *cordiumv1.Workspace) (*cordiumv1.Workspace, error)
	UpdateWorkspace(context.Context, *cordiumv1.Workspace) (*cordiumv1.Workspace, error)
	GetWorkspace(context.Context, *rmetav1.GetOptions) (*cordiumv1.Workspace, error)
	ListWorkspace(context.Context, *rmetav1.ListOptions) (*cordiumv1.WorkspaceList, error)
	DeleteWorkspace(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchWorkspace(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateSecret(context.Context, *cordiumv1.Secret) (*cordiumv1.Secret, error)
	UpdatSecret(context.Context, *cordiumv1.Secret) (*cordiumv1.Secret, error)
	GetSecret(context.Context, *rmetav1.GetOptions) (*cordiumv1.Secret, error)
	ListSecret(context.Context, *rmetav1.ListOptions) (*cordiumv1.SecretList, error)
	DeleteSecret(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchSecret(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateTemplate(context.Context, *cordiumv1.Template) (*cordiumv1.Template, error)
	UpdateTemplate(context.Context, *cordiumv1.Template) (*cordiumv1.Template, error)
	GetTemplate(context.Context, *rmetav1.GetOptions) (*cordiumv1.Template, error)
	ListTemplate(context.Context, *rmetav1.ListOptions) (*cordiumv1.TemplateList, error)
	DeleteTemplate(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchTemplate(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateSpace(context.Context, *cordiumv1.Space) (*cordiumv1.Space, error)
	UpdateSpace(context.Context, *cordiumv1.Space) (*cordiumv1.Space, error)
	GetSpace(context.Context, *rmetav1.GetOptions) (*cordiumv1.Space, error)
	ListSpace(context.Context, *rmetav1.ListOptions) (*cordiumv1.SpaceList, error)
	DeleteSpace(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchSpace(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateMembership(context.Context, *cordiumv1.Membership) (*cordiumv1.Membership, error)
	UpdateMembership(context.Context, *cordiumv1.Membership) (*cordiumv1.Membership, error)
	GetMembership(context.Context, *rmetav1.GetOptions) (*cordiumv1.Membership, error)
	ListMembership(context.Context, *rmetav1.ListOptions) (*cordiumv1.MembershipList, error)
	DeleteMembership(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	CreateGitProvider(context.Context, *cordiumv1.GitProvider) (*cordiumv1.GitProvider, error)
	UpdateGitProvider(context.Context, *cordiumv1.GitProvider) (*cordiumv1.GitProvider, error)
	GetGitProvider(context.Context, *rmetav1.GetOptions) (*cordiumv1.GitProvider, error)
	ListGitProvider(context.Context, *rmetav1.ListOptions) (*cordiumv1.GitProviderList, error)
	DeleteGitProvider(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchGitProvider(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateUserSecret(context.Context, *cordiumv1.UserSecret) (*cordiumv1.UserSecret, error)
	UpdateUserSecret(context.Context, *cordiumv1.UserSecret) (*cordiumv1.UserSecret, error)
	GetUserSecret(context.Context, *rmetav1.GetOptions) (*cordiumv1.UserSecret, error)
	ListUserSecret(context.Context, *rmetav1.ListOptions) (*cordiumv1.UserSecretList, error)
	DeleteUserSecret(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchUserSecret(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	CreateUserConfig(context.Context, *cordiumv1.UserConfig) (*cordiumv1.UserConfig, error)
	UpdateUserConfig(context.Context, *cordiumv1.UserConfig) (*cordiumv1.UserConfig, error)
	GetUserConfig(context.Context, *rmetav1.GetOptions) (*cordiumv1.UserConfig, error)
	DeleteUserConfig(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error)
	WatchUserConfig(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	GetClusterConfig(context.Context, *rmetav1.GetOptions) (*cordiumv1.ClusterConfig, error)
	UpdateClusterConfig(context.Context, *cordiumv1.ClusterConfig) (*cordiumv1.ClusterConfig, error)
	WatchClusterConfig(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) CreateWorkspace(context.Context, *cordiumv1.Workspace) (*cordiumv1.Workspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) UpdateWorkspace(context.Context, *cordiumv1.Workspace) (*cordiumv1.Workspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) GetWorkspace(context.Context, *rmetav1.GetOptions) (*cordiumv1.Workspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) ListWorkspace(context.Context, *rmetav1.ListOptions) (*cordiumv1.WorkspaceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) DeleteWorkspace(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) WatchWorkspace(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchWorkspace not implemented")
}
func (UnimplementedResourceServiceServer) CreateSecret(context.Context, *cordiumv1.Secret) (*cordiumv1.Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedResourceServiceServer) UpdatSecret(context.Context, *cordiumv1.Secret) (*cordiumv1.Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatSecret not implemented")
}
func (UnimplementedResourceServiceServer) GetSecret(context.Context, *rmetav1.GetOptions) (*cordiumv1.Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedResourceServiceServer) ListSecret(context.Context, *rmetav1.ListOptions) (*cordiumv1.SecretList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecret not implemented")
}
func (UnimplementedResourceServiceServer) DeleteSecret(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedResourceServiceServer) WatchSecret(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSecret not implemented")
}
func (UnimplementedResourceServiceServer) CreateTemplate(context.Context, *cordiumv1.Template) (*cordiumv1.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedResourceServiceServer) UpdateTemplate(context.Context, *cordiumv1.Template) (*cordiumv1.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedResourceServiceServer) GetTemplate(context.Context, *rmetav1.GetOptions) (*cordiumv1.Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedResourceServiceServer) ListTemplate(context.Context, *rmetav1.ListOptions) (*cordiumv1.TemplateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplate not implemented")
}
func (UnimplementedResourceServiceServer) DeleteTemplate(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedResourceServiceServer) WatchTemplate(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchTemplate not implemented")
}
func (UnimplementedResourceServiceServer) CreateSpace(context.Context, *cordiumv1.Space) (*cordiumv1.Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpace not implemented")
}
func (UnimplementedResourceServiceServer) UpdateSpace(context.Context, *cordiumv1.Space) (*cordiumv1.Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpace not implemented")
}
func (UnimplementedResourceServiceServer) GetSpace(context.Context, *rmetav1.GetOptions) (*cordiumv1.Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpace not implemented")
}
func (UnimplementedResourceServiceServer) ListSpace(context.Context, *rmetav1.ListOptions) (*cordiumv1.SpaceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSpace not implemented")
}
func (UnimplementedResourceServiceServer) DeleteSpace(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpace not implemented")
}
func (UnimplementedResourceServiceServer) WatchSpace(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchSpace not implemented")
}
func (UnimplementedResourceServiceServer) CreateMembership(context.Context, *cordiumv1.Membership) (*cordiumv1.Membership, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembership not implemented")
}
func (UnimplementedResourceServiceServer) UpdateMembership(context.Context, *cordiumv1.Membership) (*cordiumv1.Membership, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembership not implemented")
}
func (UnimplementedResourceServiceServer) GetMembership(context.Context, *rmetav1.GetOptions) (*cordiumv1.Membership, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembership not implemented")
}
func (UnimplementedResourceServiceServer) ListMembership(context.Context, *rmetav1.ListOptions) (*cordiumv1.MembershipList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembership not implemented")
}
func (UnimplementedResourceServiceServer) DeleteMembership(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMembership not implemented")
}
func (UnimplementedResourceServiceServer) CreateGitProvider(context.Context, *cordiumv1.GitProvider) (*cordiumv1.GitProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) UpdateGitProvider(context.Context, *cordiumv1.GitProvider) (*cordiumv1.GitProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) GetGitProvider(context.Context, *rmetav1.GetOptions) (*cordiumv1.GitProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) ListGitProvider(context.Context, *rmetav1.ListOptions) (*cordiumv1.GitProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) DeleteGitProvider(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) WatchGitProvider(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchGitProvider not implemented")
}
func (UnimplementedResourceServiceServer) CreateUserSecret(context.Context, *cordiumv1.UserSecret) (*cordiumv1.UserSecret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) UpdateUserSecret(context.Context, *cordiumv1.UserSecret) (*cordiumv1.UserSecret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) GetUserSecret(context.Context, *rmetav1.GetOptions) (*cordiumv1.UserSecret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) ListUserSecret(context.Context, *rmetav1.ListOptions) (*cordiumv1.UserSecretList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) DeleteUserSecret(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) WatchUserSecret(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchUserSecret not implemented")
}
func (UnimplementedResourceServiceServer) CreateUserConfig(context.Context, *cordiumv1.UserConfig) (*cordiumv1.UserConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserConfig not implemented")
}
func (UnimplementedResourceServiceServer) UpdateUserConfig(context.Context, *cordiumv1.UserConfig) (*cordiumv1.UserConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserConfig not implemented")
}
func (UnimplementedResourceServiceServer) GetUserConfig(context.Context, *rmetav1.GetOptions) (*cordiumv1.UserConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserConfig not implemented")
}
func (UnimplementedResourceServiceServer) DeleteUserConfig(context.Context, *rmetav1.DeleteOptions) (*rmetav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserConfig not implemented")
}
func (UnimplementedResourceServiceServer) WatchUserConfig(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchUserConfig not implemented")
}
func (UnimplementedResourceServiceServer) GetClusterConfig(context.Context, *rmetav1.GetOptions) (*cordiumv1.ClusterConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterConfig not implemented")
}
func (UnimplementedResourceServiceServer) UpdateClusterConfig(context.Context, *cordiumv1.ClusterConfig) (*cordiumv1.ClusterConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClusterConfig not implemented")
}
func (UnimplementedResourceServiceServer) WatchClusterConfig(*rmetav1.WatchOptions, grpc.ServerStreamingServer[rmetav1.WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchClusterConfig not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Workspace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateWorkspace(ctx, req.(*cordiumv1.Workspace))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Workspace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateWorkspace(ctx, req.(*cordiumv1.Workspace))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetWorkspace(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListWorkspace(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteWorkspace(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchWorkspace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchWorkspace(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchWorkspaceServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateSecret(ctx, req.(*cordiumv1.Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdatSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdatSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdatSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdatSecret(ctx, req.(*cordiumv1.Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetSecret(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListSecret(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteSecret(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchSecret_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchSecret(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchSecretServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateTemplate(ctx, req.(*cordiumv1.Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateTemplate(ctx, req.(*cordiumv1.Template))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetTemplate(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListTemplate(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteTemplate(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchTemplate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchTemplate(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchTemplateServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Space)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateSpace(ctx, req.(*cordiumv1.Space))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Space)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateSpace(ctx, req.(*cordiumv1.Space))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetSpace(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListSpace(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteSpace(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchSpace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchSpace(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchSpaceServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Membership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateMembership(ctx, req.(*cordiumv1.Membership))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.Membership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateMembership(ctx, req.(*cordiumv1.Membership))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetMembership(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListMembership(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteMembership(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_CreateGitProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.GitProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateGitProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateGitProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateGitProvider(ctx, req.(*cordiumv1.GitProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateGitProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.GitProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateGitProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateGitProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateGitProvider(ctx, req.(*cordiumv1.GitProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetGitProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetGitProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetGitProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetGitProvider(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListGitProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListGitProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListGitProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListGitProvider(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteGitProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteGitProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteGitProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteGitProvider(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchGitProvider_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchGitProvider(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchGitProviderServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateUserSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.UserSecret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateUserSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateUserSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateUserSecret(ctx, req.(*cordiumv1.UserSecret))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateUserSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.UserSecret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateUserSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateUserSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateUserSecret(ctx, req.(*cordiumv1.UserSecret))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetUserSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetUserSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetUserSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetUserSecret(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListUserSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.ListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListUserSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListUserSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListUserSecret(ctx, req.(*rmetav1.ListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteUserSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteUserSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteUserSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteUserSecret(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchUserSecret_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchUserSecret(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchUserSecretServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_CreateUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.UserConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).CreateUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_CreateUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).CreateUserConfig(ctx, req.(*cordiumv1.UserConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.UserConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateUserConfig(ctx, req.(*cordiumv1.UserConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetUserConfig(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_DeleteUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).DeleteUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_DeleteUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).DeleteUserConfig(ctx, req.(*rmetav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchUserConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchUserConfig(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchUserConfigServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

func _ResourceService_GetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rmetav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetClusterConfig(ctx, req.(*rmetav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_UpdateClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cordiumv1.ClusterConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).UpdateClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_UpdateClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).UpdateClusterConfig(ctx, req.(*cordiumv1.ClusterConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_WatchClusterConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rmetav1.WatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).WatchClusterConfig(m, &grpc.GenericServerStream[rmetav1.WatchOptions, rmetav1.WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_WatchClusterConfigServer = grpc.ServerStreamingServer[rmetav1.WatchEvent]

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.rsc.cordium.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkspace",
			Handler:    _ResourceService_CreateWorkspace_Handler,
		},
		{
			MethodName: "UpdateWorkspace",
			Handler:    _ResourceService_UpdateWorkspace_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _ResourceService_GetWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspace",
			Handler:    _ResourceService_ListWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _ResourceService_DeleteWorkspace_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _ResourceService_CreateSecret_Handler,
		},
		{
			MethodName: "UpdatSecret",
			Handler:    _ResourceService_UpdatSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _ResourceService_GetSecret_Handler,
		},
		{
			MethodName: "ListSecret",
			Handler:    _ResourceService_ListSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _ResourceService_DeleteSecret_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _ResourceService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _ResourceService_UpdateTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _ResourceService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplate",
			Handler:    _ResourceService_ListTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _ResourceService_DeleteTemplate_Handler,
		},
		{
			MethodName: "CreateSpace",
			Handler:    _ResourceService_CreateSpace_Handler,
		},
		{
			MethodName: "UpdateSpace",
			Handler:    _ResourceService_UpdateSpace_Handler,
		},
		{
			MethodName: "GetSpace",
			Handler:    _ResourceService_GetSpace_Handler,
		},
		{
			MethodName: "ListSpace",
			Handler:    _ResourceService_ListSpace_Handler,
		},
		{
			MethodName: "DeleteSpace",
			Handler:    _ResourceService_DeleteSpace_Handler,
		},
		{
			MethodName: "CreateMembership",
			Handler:    _ResourceService_CreateMembership_Handler,
		},
		{
			MethodName: "UpdateMembership",
			Handler:    _ResourceService_UpdateMembership_Handler,
		},
		{
			MethodName: "GetMembership",
			Handler:    _ResourceService_GetMembership_Handler,
		},
		{
			MethodName: "ListMembership",
			Handler:    _ResourceService_ListMembership_Handler,
		},
		{
			MethodName: "DeleteMembership",
			Handler:    _ResourceService_DeleteMembership_Handler,
		},
		{
			MethodName: "CreateGitProvider",
			Handler:    _ResourceService_CreateGitProvider_Handler,
		},
		{
			MethodName: "UpdateGitProvider",
			Handler:    _ResourceService_UpdateGitProvider_Handler,
		},
		{
			MethodName: "GetGitProvider",
			Handler:    _ResourceService_GetGitProvider_Handler,
		},
		{
			MethodName: "ListGitProvider",
			Handler:    _ResourceService_ListGitProvider_Handler,
		},
		{
			MethodName: "DeleteGitProvider",
			Handler:    _ResourceService_DeleteGitProvider_Handler,
		},
		{
			MethodName: "CreateUserSecret",
			Handler:    _ResourceService_CreateUserSecret_Handler,
		},
		{
			MethodName: "UpdateUserSecret",
			Handler:    _ResourceService_UpdateUserSecret_Handler,
		},
		{
			MethodName: "GetUserSecret",
			Handler:    _ResourceService_GetUserSecret_Handler,
		},
		{
			MethodName: "ListUserSecret",
			Handler:    _ResourceService_ListUserSecret_Handler,
		},
		{
			MethodName: "DeleteUserSecret",
			Handler:    _ResourceService_DeleteUserSecret_Handler,
		},
		{
			MethodName: "CreateUserConfig",
			Handler:    _ResourceService_CreateUserConfig_Handler,
		},
		{
			MethodName: "UpdateUserConfig",
			Handler:    _ResourceService_UpdateUserConfig_Handler,
		},
		{
			MethodName: "GetUserConfig",
			Handler:    _ResourceService_GetUserConfig_Handler,
		},
		{
			MethodName: "DeleteUserConfig",
			Handler:    _ResourceService_DeleteUserConfig_Handler,
		},
		{
			MethodName: "GetClusterConfig",
			Handler:    _ResourceService_GetClusterConfig_Handler,
		},
		{
			MethodName: "UpdateClusterConfig",
			Handler:    _ResourceService_UpdateClusterConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkspace",
			Handler:       _ResourceService_WatchWorkspace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSecret",
			Handler:       _ResourceService_WatchSecret_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTemplate",
			Handler:       _ResourceService_WatchTemplate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSpace",
			Handler:       _ResourceService_WatchSpace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchGitProvider",
			Handler:       _ResourceService_WatchGitProvider_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchUserSecret",
			Handler:       _ResourceService_WatchUserSecret_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchUserConfig",
			Handler:       _ResourceService_WatchUserConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchClusterConfig",
			Handler:       _ResourceService_WatchClusterConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rcordiumv1.proto",
}
