/*
 * Copyright Octelium Labs, LLC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ssh

import (
	"fmt"

	"github.com/juju/errors"
	"github.com/octelium/cordium/pkg/apiutils/ucordiumv1"
	pb "github.com/octelium/octelium/apis/main/cordiumv1"
	"github.com/octelium/octelium/apis/main/metav1"
	"github.com/octelium/octelium/apis/main/userv1"
	"github.com/octelium/octelium/client/common/client"
	"github.com/octelium/octelium/client/common/cliutils"
	sshc "github.com/octelium/octelium/client/octelium/commands/ssh"
	"github.com/spf13/cobra"
)

type args struct {
	LocalForwards   []string
	DynamicForwards []string
	NoCommand       bool
	PrintConfig     bool
}

var cmdArgs args

func init() {
	Cmd.Flags().StringArrayVarP(&cmdArgs.LocalForwards, "local", "L", nil,
		"Local port forward: [bind_addr:]port:host:hostport")
	Cmd.Flags().StringArrayVarP(&cmdArgs.DynamicForwards, "dynamic", "D", nil,
		"Dynamic (SOCKS5) forward: [bind_addr:]port")
	Cmd.Flags().BoolVarP(&cmdArgs.NoCommand, "no-command", "N", false,
		"Do not execute a remote command (useful for port forwarding only)")
	Cmd.Flags().BoolVar(&cmdArgs.PrintConfig, "print-config", false,
		"Print an SSH config block for this Workspace and exit")
}

var Cmd = &cobra.Command{
	Use:   "ssh <workspace-name> [-- command [args...]]",
	Short: "Open an SSH session to a Workspace",
	Long: `Open an interactive SSH session or execute a remote command on a connected
a running Workspace using its name.

A remote command and its arguments can be passed after a double-dash (--).
If no command is given, an interactive shell is opened.`,
	Example: `
  # Open an interactive shell
  octelium ssh abc

  # Run a single remote command
  octelium ssh abc -- uptime

  # Run a shell pipeline
  octelium ssh abc -- sh -c "ps aux | grep python"

  # Local port forward: forward local :5432 to remote localhost:5432
  octelium ssh abc -L 5432:localhost:5432

  # Multiple port forwards, no interactive shell
  octelium ssh abc -N \
    -L 5432:localhost:5432 \
    -L 6379:localhost:6379

  # Dynamic SOCKS5 proxy on local port 1080
  octelium ssh abc -D 1080 -N`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return doCmd(cmd, args)
	},
	Args: cobra.MinimumNArgs(1),
}

func doCmd(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()
	i, err := cliutils.GetCLIInfo(cmd, args)
	if err != nil {
		return err
	}

	wsName := args[0]

	var remoteCommand []string
	if len(args) > 1 {
		remoteCommand = args[1:]
	}

	conn, err := client.GetGRPCClientConn(ctx, i.Domain)
	if err != nil {
		return err
	}
	defer conn.Close()

	c := pb.NewMainServiceClient(conn)

	ws, err := c.GetWorkspace(ctx, &metav1.GetOptions{Name: wsName})
	if err != nil {
		return errors.Errorf("could not get Workspace %q: %+v", wsName, err)
	}
	if !ucordiumv1.ToWorkspace(ws).IsPreparingOrRunning() {
		return errors.Errorf("Workspace %q is not running (state: %s)", wsName, ws.Status.State.String())
	}

	if cmdArgs.PrintConfig {
		userC := userv1.NewMainServiceClient(conn)
		cfg, err := userC.SetServiceConfigs(ctx, &userv1.SetServiceConfigsRequest{
			Name: fmt.Sprintf("%s-ssh.cordium", ws.Status.RegionRef.Name),
		})
		if err != nil {
			return err
		}

		fmt.Print(renderSSHConfig(cfg.Host, ws.Metadata.Name, int(cfg.Port)))
		return nil
	}

	return sshc.DoCommand(ctx, &sshc.DoCommandOpts{
		Domain:          i.Domain,
		Service:         fmt.Sprintf("%s-ssh.cordium", ws.Status.RegionRef.Name),
		SSHUser:         wsName,
		Command:         remoteCommand,
		NoCommand:       cmdArgs.NoCommand,
		DynamicForwards: cmdArgs.DynamicForwards,
		LocalForwards:   cmdArgs.LocalForwards,
	})
}

func renderSSHConfig(host, wsName string, port int) string {
	return fmt.Sprintf(`# Cordium Workspace: %s
# Add this block to ~/.ssh/config
# Generated by: cordium ssh %s --print-config

Host cordium-%s
    HostName %s
    User %s
    Port %d

    BatchMode yes
    PreferredAuthentications none
    PubkeyAuthentication no
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    HostbasedAuthentication no
    NumberOfPasswordPrompts 0

    ForwardAgent no
    ForwardX11 no

    ControlMaster auto
    ControlPath ~/.ssh/cordium-%%C
    ControlPersist 10m

    HostKeyAlias cordium-%s
    StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
    CheckHostIP no

    ConnectTimeout 10
    ConnectionAttempts 1
    ServerAliveInterval 30
    ServerAliveCountMax 3

    LogLevel ERROR
`, wsName, wsName, wsName, host, wsName, port, wsName)
}
