/*
 * Copyright Octelium Labs, LLC. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License version 3,
 * as published by the Free Software Foundation of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: cbootstrapv1.proto

package cbootstrapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_Spec_Network_Mode int32

const (
	// DEFAULT defaults to DUAL_STACK
	Config_Spec_Network_DEFAULT Config_Spec_Network_Mode = 0
	// DUAL_STACK sets the Cluster to operate in dual-stack mode.
	// Services receive dual-stack private addresses and clients can connect
	// in dual-stack mode, IPv4-only or IPv6-only modes.
	Config_Spec_Network_DUAL_STACK Config_Spec_Network_Mode = 1
	// V6_ONLY sets the Cluster to operate in IPv6-only mode.
	// Services receive IPv6-only private addresses and clients can connect
	// only connect via IPv6-only modes.
	Config_Spec_Network_V6_ONLY Config_Spec_Network_Mode = 2
	// V4_ONLY sets the Cluster to operate in IPv4-only mode.
	// Services receive IPv4-only private addresses and clients can connect
	// only connect via IPv4-only modes.
	Config_Spec_Network_V4_ONLY Config_Spec_Network_Mode = 3
)

// Enum value maps for Config_Spec_Network_Mode.
var (
	Config_Spec_Network_Mode_name = map[int32]string{
		0: "DEFAULT",
		1: "DUAL_STACK",
		2: "V6_ONLY",
		3: "V4_ONLY",
	}
	Config_Spec_Network_Mode_value = map[string]int32{
		"DEFAULT":    0,
		"DUAL_STACK": 1,
		"V6_ONLY":    2,
		"V4_ONLY":    3,
	}
)

func (x Config_Spec_Network_Mode) Enum() *Config_Spec_Network_Mode {
	p := new(Config_Spec_Network_Mode)
	*p = x
	return p
}

func (x Config_Spec_Network_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Spec_Network_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_cbootstrapv1_proto_enumTypes[0].Descriptor()
}

func (Config_Spec_Network_Mode) Type() protoreflect.EnumType {
	return &file_cbootstrapv1_proto_enumTypes[0]
}

func (x Config_Spec_Network_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Spec_Network_Mode.Descriptor instead.
func (Config_Spec_Network_Mode) EnumDescriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3, 0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string       `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Spec       *Config_Spec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Config_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Config_Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          string                        `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PrimaryStorage   *Config_Spec_PrimaryStorage   `protobuf:"bytes,2,opt,name=primaryStorage,proto3" json:"primaryStorage,omitempty"`
	SecondaryStorage *Config_Spec_SecondaryStorage `protobuf:"bytes,3,opt,name=secondaryStorage,proto3" json:"secondaryStorage,omitempty"`
	Kubernetes       *Config_Spec_Kubernetes       `protobuf:"bytes,4,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Network          *Config_Spec_Network          `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Provider         *Config_Spec_Provider         `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *Config_Spec) Reset() {
	*x = Config_Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec) ProtoMessage() {}

func (x *Config_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec.ProtoReflect.Descriptor instead.
func (*Config_Spec) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_Spec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config_Spec) GetPrimaryStorage() *Config_Spec_PrimaryStorage {
	if x != nil {
		return x.PrimaryStorage
	}
	return nil
}

func (x *Config_Spec) GetSecondaryStorage() *Config_Spec_SecondaryStorage {
	if x != nil {
		return x.SecondaryStorage
	}
	return nil
}

func (x *Config_Spec) GetKubernetes() *Config_Spec_Kubernetes {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *Config_Spec) GetNetwork() *Config_Spec_Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Config_Spec) GetProvider() *Config_Spec_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type Config_Spec_PrimaryStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Config_Spec_PrimaryStorage_Postgresql_
	Type isConfig_Spec_PrimaryStorage_Type `protobuf_oneof:"type"`
}

func (x *Config_Spec_PrimaryStorage) Reset() {
	*x = Config_Spec_PrimaryStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_PrimaryStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_PrimaryStorage) ProtoMessage() {}

func (x *Config_Spec_PrimaryStorage) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_PrimaryStorage.ProtoReflect.Descriptor instead.
func (*Config_Spec_PrimaryStorage) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (m *Config_Spec_PrimaryStorage) GetType() isConfig_Spec_PrimaryStorage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Config_Spec_PrimaryStorage) GetPostgresql() *Config_Spec_PrimaryStorage_Postgresql {
	if x, ok := x.GetType().(*Config_Spec_PrimaryStorage_Postgresql_); ok {
		return x.Postgresql
	}
	return nil
}

type isConfig_Spec_PrimaryStorage_Type interface {
	isConfig_Spec_PrimaryStorage_Type()
}

type Config_Spec_PrimaryStorage_Postgresql_ struct {
	Postgresql *Config_Spec_PrimaryStorage_Postgresql `protobuf:"bytes,1,opt,name=postgresql,proto3,oneof"`
}

func (*Config_Spec_PrimaryStorage_Postgresql_) isConfig_Spec_PrimaryStorage_Type() {}

type Config_Spec_SecondaryStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Config_Spec_SecondaryStorage_Redis_
	Type isConfig_Spec_SecondaryStorage_Type `protobuf_oneof:"type"`
}

func (x *Config_Spec_SecondaryStorage) Reset() {
	*x = Config_Spec_SecondaryStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_SecondaryStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_SecondaryStorage) ProtoMessage() {}

func (x *Config_Spec_SecondaryStorage) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_SecondaryStorage.ProtoReflect.Descriptor instead.
func (*Config_Spec_SecondaryStorage) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (m *Config_Spec_SecondaryStorage) GetType() isConfig_Spec_SecondaryStorage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Config_Spec_SecondaryStorage) GetRedis() *Config_Spec_SecondaryStorage_Redis {
	if x, ok := x.GetType().(*Config_Spec_SecondaryStorage_Redis_); ok {
		return x.Redis
	}
	return nil
}

type isConfig_Spec_SecondaryStorage_Type interface {
	isConfig_Spec_SecondaryStorage_Type()
}

type Config_Spec_SecondaryStorage_Redis_ struct {
	Redis *Config_Spec_SecondaryStorage_Redis `protobuf:"bytes,1,opt,name=redis,proto3,oneof"`
}

func (*Config_Spec_SecondaryStorage_Redis_) isConfig_Spec_SecondaryStorage_Type() {}

type Config_Spec_Kubernetes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CniBinDir string `protobuf:"bytes,2,opt,name=cniBinDir,proto3" json:"cniBinDir,omitempty"`
	IsCRIO    bool   `protobuf:"varint,3,opt,name=isCRIO,proto3" json:"isCRIO,omitempty"`
}

func (x *Config_Spec_Kubernetes) Reset() {
	*x = Config_Spec_Kubernetes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Kubernetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Kubernetes) ProtoMessage() {}

func (x *Config_Spec_Kubernetes) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Kubernetes.ProtoReflect.Descriptor instead.
func (*Config_Spec_Kubernetes) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Config_Spec_Kubernetes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config_Spec_Kubernetes) GetCniBinDir() string {
	if x != nil {
		return x.CniBinDir
	}
	return ""
}

func (x *Config_Spec_Kubernetes) GetIsCRIO() bool {
	if x != nil {
		return x.IsCRIO
	}
	return false
}

type Config_Spec_Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mode sets the networking mode (DualStack, IPv4Only or IPv6Only) for
	// the Cluster's Networks. This can only be effective when set prior to
	// the Cluster installation or upgrade.
	Mode Config_Spec_Network_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=octelium.api.cluster.bootstrap.v1.Config_Spec_Network_Mode" json:"mode,omitempty"`
	// V4 sets IPv4 Network configurations.
	V4 *Config_Spec_Network_V4 `protobuf:"bytes,2,opt,name=v4,proto3" json:"v4,omitempty"`
	// V6 sets IPv6 Network configurations.
	V6 *Config_Spec_Network_V6 `protobuf:"bytes,3,opt,name=v6,proto3" json:"v6,omitempty"`
	// Wireguard sets the Wireguard-specific configuration
	Wireguard *Config_Spec_Network_Wireguard `protobuf:"bytes,4,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	// QUICV0 (EXPIREMENTAL) sets the QUICv0-specific configuration
	Quicv0 *Config_Spec_Network_QUICV0 `protobuf:"bytes,5,opt,name=quicv0,proto3" json:"quicv0,omitempty"`
}

func (x *Config_Spec_Network) Reset() {
	*x = Config_Spec_Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Network) ProtoMessage() {}

func (x *Config_Spec_Network) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Network.ProtoReflect.Descriptor instead.
func (*Config_Spec_Network) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Config_Spec_Network) GetMode() Config_Spec_Network_Mode {
	if x != nil {
		return x.Mode
	}
	return Config_Spec_Network_DEFAULT
}

func (x *Config_Spec_Network) GetV4() *Config_Spec_Network_V4 {
	if x != nil {
		return x.V4
	}
	return nil
}

func (x *Config_Spec_Network) GetV6() *Config_Spec_Network_V6 {
	if x != nil {
		return x.V6
	}
	return nil
}

func (x *Config_Spec_Network) GetWireguard() *Config_Spec_Network_Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *Config_Spec_Network) GetQuicv0() *Config_Spec_Network_QUICV0 {
	if x != nil {
		return x.Quicv0
	}
	return nil
}

type Config_Spec_Provider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Config_Spec_Provider_Linode_
	//	*Config_Spec_Provider_Digitalocean
	//	*Config_Spec_Provider_Gcp
	//	*Config_Spec_Provider_Aws
	//	*Config_Spec_Provider_Hetzner_
	//	*Config_Spec_Provider_Vultr_
	Type isConfig_Spec_Provider_Type `protobuf_oneof:"type"`
}

func (x *Config_Spec_Provider) Reset() {
	*x = Config_Spec_Provider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider) ProtoMessage() {}

func (x *Config_Spec_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (m *Config_Spec_Provider) GetType() isConfig_Spec_Provider_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Config_Spec_Provider) GetLinode() *Config_Spec_Provider_Linode {
	if x, ok := x.GetType().(*Config_Spec_Provider_Linode_); ok {
		return x.Linode
	}
	return nil
}

func (x *Config_Spec_Provider) GetDigitalocean() *Config_Spec_Provider_DigitalOcean {
	if x, ok := x.GetType().(*Config_Spec_Provider_Digitalocean); ok {
		return x.Digitalocean
	}
	return nil
}

func (x *Config_Spec_Provider) GetGcp() *Config_Spec_Provider_GCP {
	if x, ok := x.GetType().(*Config_Spec_Provider_Gcp); ok {
		return x.Gcp
	}
	return nil
}

func (x *Config_Spec_Provider) GetAws() *Config_Spec_Provider_AWS {
	if x, ok := x.GetType().(*Config_Spec_Provider_Aws); ok {
		return x.Aws
	}
	return nil
}

func (x *Config_Spec_Provider) GetHetzner() *Config_Spec_Provider_Hetzner {
	if x, ok := x.GetType().(*Config_Spec_Provider_Hetzner_); ok {
		return x.Hetzner
	}
	return nil
}

func (x *Config_Spec_Provider) GetVultr() *Config_Spec_Provider_Vultr {
	if x, ok := x.GetType().(*Config_Spec_Provider_Vultr_); ok {
		return x.Vultr
	}
	return nil
}

type isConfig_Spec_Provider_Type interface {
	isConfig_Spec_Provider_Type()
}

type Config_Spec_Provider_Linode_ struct {
	Linode *Config_Spec_Provider_Linode `protobuf:"bytes,1,opt,name=linode,proto3,oneof"`
}

type Config_Spec_Provider_Digitalocean struct {
	Digitalocean *Config_Spec_Provider_DigitalOcean `protobuf:"bytes,2,opt,name=digitalocean,proto3,oneof"`
}

type Config_Spec_Provider_Gcp struct {
	Gcp *Config_Spec_Provider_GCP `protobuf:"bytes,3,opt,name=gcp,proto3,oneof"`
}

type Config_Spec_Provider_Aws struct {
	Aws *Config_Spec_Provider_AWS `protobuf:"bytes,4,opt,name=aws,proto3,oneof"`
}

type Config_Spec_Provider_Hetzner_ struct {
	Hetzner *Config_Spec_Provider_Hetzner `protobuf:"bytes,5,opt,name=hetzner,proto3,oneof"`
}

type Config_Spec_Provider_Vultr_ struct {
	Vultr *Config_Spec_Provider_Vultr `protobuf:"bytes,6,opt,name=vultr,proto3,oneof"`
}

func (*Config_Spec_Provider_Linode_) isConfig_Spec_Provider_Type() {}

func (*Config_Spec_Provider_Digitalocean) isConfig_Spec_Provider_Type() {}

func (*Config_Spec_Provider_Gcp) isConfig_Spec_Provider_Type() {}

func (*Config_Spec_Provider_Aws) isConfig_Spec_Provider_Type() {}

func (*Config_Spec_Provider_Hetzner_) isConfig_Spec_Provider_Type() {}

func (*Config_Spec_Provider_Vultr_) isConfig_Spec_Provider_Type() {}

type Config_Spec_PrimaryStorage_Postgresql struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Database string `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	NoSSL    bool   `protobuf:"varint,6,opt,name=noSSL,proto3" json:"noSSL,omitempty"`
}

func (x *Config_Spec_PrimaryStorage_Postgresql) Reset() {
	*x = Config_Spec_PrimaryStorage_Postgresql{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_PrimaryStorage_Postgresql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_PrimaryStorage_Postgresql) ProtoMessage() {}

func (x *Config_Spec_PrimaryStorage_Postgresql) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_PrimaryStorage_Postgresql.ProtoReflect.Descriptor instead.
func (*Config_Spec_PrimaryStorage_Postgresql) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Config_Spec_PrimaryStorage_Postgresql) GetNoSSL() bool {
	if x != nil {
		return x.NoSSL
	}
	return false
}

type Config_Spec_SecondaryStorage_Redis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Database int32  `protobuf:"varint,5,opt,name=database,proto3" json:"database,omitempty"`
	UseTLS   bool   `protobuf:"varint,6,opt,name=useTLS,proto3" json:"useTLS,omitempty"`
}

func (x *Config_Spec_SecondaryStorage_Redis) Reset() {
	*x = Config_Spec_SecondaryStorage_Redis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_SecondaryStorage_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_SecondaryStorage_Redis) ProtoMessage() {}

func (x *Config_Spec_SecondaryStorage_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_SecondaryStorage_Redis.ProtoReflect.Descriptor instead.
func (*Config_Spec_SecondaryStorage_Redis) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *Config_Spec_SecondaryStorage_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config_Spec_SecondaryStorage_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config_Spec_SecondaryStorage_Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config_Spec_SecondaryStorage_Redis) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Config_Spec_SecondaryStorage_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *Config_Spec_SecondaryStorage_Redis) GetUseTLS() bool {
	if x != nil {
		return x.UseTLS
	}
	return false
}

type Config_Spec_Network_V4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ClusterNetwork is the Cluster network range. Currently
	// `100.64.0.0/10` is used by default.
	ClusterNetwork string `protobuf:"bytes,1,opt,name=clusterNetwork,proto3" json:"clusterNetwork,omitempty"`
}

func (x *Config_Spec_Network_V4) Reset() {
	*x = Config_Spec_Network_V4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Network_V4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Network_V4) ProtoMessage() {}

func (x *Config_Spec_Network_V4) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Network_V4.ProtoReflect.Descriptor instead.
func (*Config_Spec_Network_V4) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3, 0}
}

func (x *Config_Spec_Network_V4) GetClusterNetwork() string {
	if x != nil {
		return x.ClusterNetwork
	}
	return ""
}

type Config_Spec_Network_V6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ClusterNetwork is the Cluster network range. Currently not enforced
	// as the Cluster automatically chooses the Network ranges.
	ClusterNetwork string `protobuf:"bytes,1,opt,name=clusterNetwork,proto3" json:"clusterNetwork,omitempty"`
}

func (x *Config_Spec_Network_V6) Reset() {
	*x = Config_Spec_Network_V6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Network_V6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Network_V6) ProtoMessage() {}

func (x *Config_Spec_Network_V6) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Network_V6.ProtoReflect.Descriptor instead.
func (*Config_Spec_Network_V6) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3, 1}
}

func (x *Config_Spec_Network_V6) GetClusterNetwork() string {
	if x != nil {
		return x.ClusterNetwork
	}
	return ""
}

type Config_Spec_Network_Wireguard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// GatewayPort sets the Gateway port. By default it is set to 53820
	GatewayPort uint32 `protobuf:"varint,1,opt,name=gatewayPort,proto3" json:"gatewayPort,omitempty"`
	// MTU overrides the default value used for the Gateway interface's MTU.
	Mtu uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *Config_Spec_Network_Wireguard) Reset() {
	*x = Config_Spec_Network_Wireguard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Network_Wireguard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Network_Wireguard) ProtoMessage() {}

func (x *Config_Spec_Network_Wireguard) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Network_Wireguard.ProtoReflect.Descriptor instead.
func (*Config_Spec_Network_Wireguard) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3, 2}
}

func (x *Config_Spec_Network_Wireguard) GetGatewayPort() uint32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *Config_Spec_Network_Wireguard) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type Config_Spec_Network_QUICV0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Enable enables QUICv0 gateways. By default this mode is not enabled.
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	// GatewayPort sets the Gateway port. By default it is set to 8443
	GatewayPort uint32 `protobuf:"varint,2,opt,name=gatewayPort,proto3" json:"gatewayPort,omitempty"`
	// MTU overrides the default value used for the Gateway interface's MTU.
	Mtu uint32 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *Config_Spec_Network_QUICV0) Reset() {
	*x = Config_Spec_Network_QUICV0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Network_QUICV0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Network_QUICV0) ProtoMessage() {}

func (x *Config_Spec_Network_QUICV0) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Network_QUICV0.ProtoReflect.Descriptor instead.
func (*Config_Spec_Network_QUICV0) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 3, 3}
}

func (x *Config_Spec_Network_QUICV0) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Config_Spec_Network_QUICV0) GetGatewayPort() uint32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *Config_Spec_Network_QUICV0) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type Config_Spec_Provider_Hetzner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *Config_Spec_Provider_Hetzner) Reset() {
	*x = Config_Spec_Provider_Hetzner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_Hetzner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_Hetzner) ProtoMessage() {}

func (x *Config_Spec_Provider_Hetzner) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_Hetzner.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_Hetzner) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 0}
}

func (x *Config_Spec_Provider_Hetzner) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Config_Spec_Provider_Hetzner) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Config_Spec_Provider_Hetzner) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type Config_Spec_Provider_Vultr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey   string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	PlanID   int64  `protobuf:"varint,2,opt,name=planID,proto3" json:"planID,omitempty"`
	RegionID int64  `protobuf:"varint,3,opt,name=regionID,proto3" json:"regionID,omitempty"`
}

func (x *Config_Spec_Provider_Vultr) Reset() {
	*x = Config_Spec_Provider_Vultr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_Vultr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_Vultr) ProtoMessage() {}

func (x *Config_Spec_Provider_Vultr) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_Vultr.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_Vultr) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 1}
}

func (x *Config_Spec_Provider_Vultr) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Config_Spec_Provider_Vultr) GetPlanID() int64 {
	if x != nil {
		return x.PlanID
	}
	return 0
}

func (x *Config_Spec_Provider_Vultr) GetRegionID() int64 {
	if x != nil {
		return x.RegionID
	}
	return 0
}

type Config_Spec_Provider_GCP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Zone          string `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Region        string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	MachineTypeID string `protobuf:"bytes,4,opt,name=machineTypeID,proto3" json:"machineTypeID,omitempty"`
}

func (x *Config_Spec_Provider_GCP) Reset() {
	*x = Config_Spec_Provider_GCP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_GCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_GCP) ProtoMessage() {}

func (x *Config_Spec_Provider_GCP) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_GCP.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_GCP) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 2}
}

func (x *Config_Spec_Provider_GCP) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Config_Spec_Provider_GCP) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Config_Spec_Provider_GCP) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Config_Spec_Provider_GCP) GetMachineTypeID() string {
	if x != nil {
		return x.MachineTypeID
	}
	return ""
}

type Config_Spec_Provider_DigitalOcean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey               string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Region               string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Size                 string `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	UseIPv6              bool   `protobuf:"varint,4,opt,name=useIPv6,proto3" json:"useIPv6,omitempty"`
	UsePrivateNetworking bool   `protobuf:"varint,5,opt,name=usePrivateNetworking,proto3" json:"usePrivateNetworking,omitempty"`
}

func (x *Config_Spec_Provider_DigitalOcean) Reset() {
	*x = Config_Spec_Provider_DigitalOcean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_DigitalOcean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_DigitalOcean) ProtoMessage() {}

func (x *Config_Spec_Provider_DigitalOcean) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_DigitalOcean.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_DigitalOcean) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 3}
}

func (x *Config_Spec_Provider_DigitalOcean) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Config_Spec_Provider_DigitalOcean) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Config_Spec_Provider_DigitalOcean) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Config_Spec_Provider_DigitalOcean) GetUseIPv6() bool {
	if x != nil {
		return x.UseIPv6
	}
	return false
}

func (x *Config_Spec_Provider_DigitalOcean) GetUsePrivateNetworking() bool {
	if x != nil {
		return x.UsePrivateNetworking
	}
	return false
}

type Config_Spec_Provider_Linode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Config_Spec_Provider_Linode) Reset() {
	*x = Config_Spec_Provider_Linode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_Linode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_Linode) ProtoMessage() {}

func (x *Config_Spec_Provider_Linode) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_Linode.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_Linode) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 4}
}

func (x *Config_Spec_Provider_Linode) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Config_Spec_Provider_Linode) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Config_Spec_Provider_Linode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Config_Spec_Provider_AWS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region              string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	SecurityGroupIDs    []string `protobuf:"bytes,3,rep,name=securityGroupIDs,proto3" json:"securityGroupIDs,omitempty"`
	Type                string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreateSecurityGroup bool     `protobuf:"varint,5,opt,name=createSecurityGroup,proto3" json:"createSecurityGroup,omitempty"`
	SubnetID            string   `protobuf:"bytes,6,opt,name=subnetID,proto3" json:"subnetID,omitempty"`
	SecurityGroupName   string   `protobuf:"bytes,7,opt,name=securityGroupName,proto3" json:"securityGroupName,omitempty"`
	SecurityGroupID     string   `protobuf:"bytes,8,opt,name=securityGroupID,proto3" json:"securityGroupID,omitempty"`
}

func (x *Config_Spec_Provider_AWS) Reset() {
	*x = Config_Spec_Provider_AWS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cbootstrapv1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Spec_Provider_AWS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Spec_Provider_AWS) ProtoMessage() {}

func (x *Config_Spec_Provider_AWS) ProtoReflect() protoreflect.Message {
	mi := &file_cbootstrapv1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Spec_Provider_AWS.ProtoReflect.Descriptor instead.
func (*Config_Spec_Provider_AWS) Descriptor() ([]byte, []int) {
	return file_cbootstrapv1_proto_rawDescGZIP(), []int{0, 0, 4, 5}
}

func (x *Config_Spec_Provider_AWS) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Config_Spec_Provider_AWS) GetSecurityGroupIDs() []string {
	if x != nil {
		return x.SecurityGroupIDs
	}
	return nil
}

func (x *Config_Spec_Provider_AWS) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Config_Spec_Provider_AWS) GetCreateSecurityGroup() bool {
	if x != nil {
		return x.CreateSecurityGroup
	}
	return false
}

func (x *Config_Spec_Provider_AWS) GetSubnetID() string {
	if x != nil {
		return x.SubnetID
	}
	return ""
}

func (x *Config_Spec_Provider_AWS) GetSecurityGroupName() string {
	if x != nil {
		return x.SecurityGroupName
	}
	return ""
}

func (x *Config_Spec_Provider_AWS) GetSecurityGroupID() string {
	if x != nil {
		return x.SecurityGroupID
	}
	return ""
}

var File_cbootstrapv1_proto protoreflect.FileDescriptor

var file_cbootstrapv1_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x22, 0xa0, 0x1a, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x1a, 0xb1, 0x19, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x65, 0x0a, 0x0e, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3d, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x6b, 0x0a, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x6f, 0x63, 0x74,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x10, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x59, 0x0a,
	0x0a, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x39, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x6b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6f, 0x63, 0x74, 0x65,
	0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x53, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x6f,
	0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x1a,
	0xa5, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x6a, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x71, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x48, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x71, 0x6c,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x71, 0x6c, 0x1a, 0x9e,
	0x01, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x71, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x53,
	0x53, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e, 0x6f, 0x53, 0x53, 0x4c, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x97, 0x02, 0x0a, 0x10, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x05,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6f, 0x63,
	0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x1a, 0x9b, 0x01, 0x0a, 0x05,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x54, 0x4c, 0x53, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x54, 0x4c, 0x53, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x1a, 0x5c, 0x0a, 0x0a, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6e, 0x69,
	0x42, 0x69, 0x6e, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6e,
	0x69, 0x42, 0x69, 0x6e, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x43, 0x52, 0x49,
	0x4f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x43, 0x52, 0x49, 0x4f, 0x1a,
	0xd9, 0x05, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x4f, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x6f, 0x63, 0x74, 0x65,
	0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x49, 0x0a, 0x02,
	0x76, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x56, 0x34, 0x52, 0x02, 0x76, 0x34, 0x12, 0x49, 0x0a, 0x02, 0x76, 0x36, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x56, 0x36, 0x52, 0x02,
	0x76, 0x36, 0x12, 0x5e, 0x0a, 0x09, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f,
	0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x09, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x12, 0x55, 0x0a, 0x06, 0x71, 0x75, 0x69, 0x63, 0x76, 0x30, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x51, 0x55, 0x49, 0x43, 0x56,
	0x30, 0x52, 0x06, 0x71, 0x75, 0x69, 0x63, 0x76, 0x30, 0x1a, 0x2c, 0x0a, 0x02, 0x56, 0x34, 0x12,
	0x26, 0x0a, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x2c, 0x0a, 0x02, 0x56, 0x36, 0x12, 0x26, 0x0a,
	0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x3f, 0x0a, 0x09, 0x57, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x1a, 0x54, 0x0a, 0x06, 0x51, 0x55, 0x49, 0x43, 0x56, 0x30,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74,
	0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x22, 0x3d, 0x0a, 0x04,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x55, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x43, 0x4b, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x36, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x56, 0x34, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x03, 0x1a, 0xbc, 0x0a, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x6a, 0x0a, 0x0c, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x6f, 0x63, 0x65,
	0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4f, 0x63, 0x65, 0x61, 0x6e, 0x48, 0x00,
	0x52, 0x0c, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x6f, 0x63, 0x65, 0x61, 0x6e, 0x12, 0x4f,
	0x0a, 0x03, 0x67, 0x63, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6f, 0x63,
	0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x43, 0x50, 0x48, 0x00, 0x52, 0x03, 0x67, 0x63, 0x70, 0x12,
	0x4f, 0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6f,
	0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x57, 0x53, 0x48, 0x00, 0x52, 0x03, 0x61, 0x77, 0x73,
	0x12, 0x5b, 0x0a, 0x07, 0x68, 0x65, 0x74, 0x7a, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3f, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x74, 0x7a, 0x6e,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x68, 0x65, 0x74, 0x7a, 0x6e, 0x65, 0x72, 0x12, 0x55, 0x0a,
	0x05, 0x76, 0x75, 0x6c, 0x74, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x6f,
	0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x56, 0x75, 0x6c, 0x74, 0x72, 0x48, 0x00, 0x52, 0x05, 0x76,
	0x75, 0x6c, 0x74, 0x72, 0x1a, 0x4d, 0x0a, 0x07, 0x48, 0x65, 0x74, 0x7a, 0x6e, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x1a, 0x53, 0x0a, 0x05, 0x56, 0x75, 0x6c, 0x74, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x1a, 0x71, 0x0a, 0x03, 0x47, 0x43, 0x50, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x1a, 0xa0, 0x01, 0x0a, 0x0c,
	0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4f, 0x63, 0x65, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x49, 0x50, 0x76, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x75, 0x73, 0x65, 0x49, 0x50, 0x76, 0x36, 0x12, 0x32, 0x0a, 0x14, 0x75, 0x73,
	0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x75, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x4c,
	0x0a, 0x06, 0x4c, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x83, 0x02, 0x0a,
	0x03, 0x41, 0x57, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x13,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x44, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f,
	0x63, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cbootstrapv1_proto_rawDescOnce sync.Once
	file_cbootstrapv1_proto_rawDescData = file_cbootstrapv1_proto_rawDesc
)

func file_cbootstrapv1_proto_rawDescGZIP() []byte {
	file_cbootstrapv1_proto_rawDescOnce.Do(func() {
		file_cbootstrapv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_cbootstrapv1_proto_rawDescData)
	})
	return file_cbootstrapv1_proto_rawDescData
}

var file_cbootstrapv1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cbootstrapv1_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cbootstrapv1_proto_goTypes = []interface{}{
	(Config_Spec_Network_Mode)(0),                 // 0: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.Mode
	(*Config)(nil),                                // 1: octelium.api.cluster.bootstrap.v1.Config
	(*Config_Spec)(nil),                           // 2: octelium.api.cluster.bootstrap.v1.Config.Spec
	(*Config_Spec_PrimaryStorage)(nil),            // 3: octelium.api.cluster.bootstrap.v1.Config.Spec.PrimaryStorage
	(*Config_Spec_SecondaryStorage)(nil),          // 4: octelium.api.cluster.bootstrap.v1.Config.Spec.SecondaryStorage
	(*Config_Spec_Kubernetes)(nil),                // 5: octelium.api.cluster.bootstrap.v1.Config.Spec.Kubernetes
	(*Config_Spec_Network)(nil),                   // 6: octelium.api.cluster.bootstrap.v1.Config.Spec.Network
	(*Config_Spec_Provider)(nil),                  // 7: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider
	(*Config_Spec_PrimaryStorage_Postgresql)(nil), // 8: octelium.api.cluster.bootstrap.v1.Config.Spec.PrimaryStorage.Postgresql
	(*Config_Spec_SecondaryStorage_Redis)(nil),    // 9: octelium.api.cluster.bootstrap.v1.Config.Spec.SecondaryStorage.Redis
	(*Config_Spec_Network_V4)(nil),                // 10: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.V4
	(*Config_Spec_Network_V6)(nil),                // 11: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.V6
	(*Config_Spec_Network_Wireguard)(nil),         // 12: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.Wireguard
	(*Config_Spec_Network_QUICV0)(nil),            // 13: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.QUICV0
	(*Config_Spec_Provider_Hetzner)(nil),          // 14: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Hetzner
	(*Config_Spec_Provider_Vultr)(nil),            // 15: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Vultr
	(*Config_Spec_Provider_GCP)(nil),              // 16: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.GCP
	(*Config_Spec_Provider_DigitalOcean)(nil),     // 17: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.DigitalOcean
	(*Config_Spec_Provider_Linode)(nil),           // 18: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Linode
	(*Config_Spec_Provider_AWS)(nil),              // 19: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.AWS
}
var file_cbootstrapv1_proto_depIdxs = []int32{
	2,  // 0: octelium.api.cluster.bootstrap.v1.Config.spec:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec
	3,  // 1: octelium.api.cluster.bootstrap.v1.Config.Spec.primaryStorage:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.PrimaryStorage
	4,  // 2: octelium.api.cluster.bootstrap.v1.Config.Spec.secondaryStorage:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.SecondaryStorage
	5,  // 3: octelium.api.cluster.bootstrap.v1.Config.Spec.kubernetes:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Kubernetes
	6,  // 4: octelium.api.cluster.bootstrap.v1.Config.Spec.network:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network
	7,  // 5: octelium.api.cluster.bootstrap.v1.Config.Spec.provider:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider
	8,  // 6: octelium.api.cluster.bootstrap.v1.Config.Spec.PrimaryStorage.postgresql:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.PrimaryStorage.Postgresql
	9,  // 7: octelium.api.cluster.bootstrap.v1.Config.Spec.SecondaryStorage.redis:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.SecondaryStorage.Redis
	0,  // 8: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.mode:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network.Mode
	10, // 9: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.v4:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network.V4
	11, // 10: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.v6:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network.V6
	12, // 11: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.wireguard:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network.Wireguard
	13, // 12: octelium.api.cluster.bootstrap.v1.Config.Spec.Network.quicv0:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Network.QUICV0
	18, // 13: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.linode:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Linode
	17, // 14: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.digitalocean:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.DigitalOcean
	16, // 15: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.gcp:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.GCP
	19, // 16: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.aws:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.AWS
	14, // 17: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.hetzner:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Hetzner
	15, // 18: octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.vultr:type_name -> octelium.api.cluster.bootstrap.v1.Config.Spec.Provider.Vultr
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_cbootstrapv1_proto_init() }
func file_cbootstrapv1_proto_init() {
	if File_cbootstrapv1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cbootstrapv1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_PrimaryStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_SecondaryStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Kubernetes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_PrimaryStorage_Postgresql); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_SecondaryStorage_Redis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Network_V4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Network_V6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Network_Wireguard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Network_QUICV0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_Hetzner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_Vultr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_GCP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_DigitalOcean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_Linode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cbootstrapv1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Spec_Provider_AWS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cbootstrapv1_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Config_Spec_PrimaryStorage_Postgresql_)(nil),
	}
	file_cbootstrapv1_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Config_Spec_SecondaryStorage_Redis_)(nil),
	}
	file_cbootstrapv1_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Config_Spec_Provider_Linode_)(nil),
		(*Config_Spec_Provider_Digitalocean)(nil),
		(*Config_Spec_Provider_Gcp)(nil),
		(*Config_Spec_Provider_Aws)(nil),
		(*Config_Spec_Provider_Hetzner_)(nil),
		(*Config_Spec_Provider_Vultr_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cbootstrapv1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cbootstrapv1_proto_goTypes,
		DependencyIndexes: file_cbootstrapv1_proto_depIdxs,
		EnumInfos:         file_cbootstrapv1_proto_enumTypes,
		MessageInfos:      file_cbootstrapv1_proto_msgTypes,
	}.Build()
	File_cbootstrapv1_proto = out.File
	file_cbootstrapv1_proto_rawDesc = nil
	file_cbootstrapv1_proto_goTypes = nil
	file_cbootstrapv1_proto_depIdxs = nil
}
