import Meta from "@/components/Meta";
import MetadataEdit from "@/components/MetadataEdit";
import PageHeader from "@/components/PageHeader";
import Panel, { PanelBody, PanelFooter, PanelHeader } from "@/components/Panel";
import SecretValueInput from "@/components/SecretValueInput";
import { onError } from "@/utils";
import { getClientWorkspace } from "@/utils/client";
import { useAppSelector } from "@/utils/hooks";
import { invalidateUserSecrets } from "@/utils/octelium";
import { Alert, Button, SegmentedControl, Stack, Text } from "@mantine/core";
import * as WsPB from "@octelium/apis/main/cordiumv1";
import { IconInfoCircle, IconKey, IconLock } from "@tabler/icons-react";
import { useMutation } from "@tanstack/react-query";
import * as React from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";

const Type = WsPB.UserSecret_Spec_Type;

const CreateUserSecret = () => {
  const client = getClientWorkspace();
  const navigate = useNavigate();
  const user = useAppSelector((a) => a.settings.status?.user);

  const [req, setReq] = React.useState(
    WsPB.UserSecret.create({
      apiVersion: "cordium/v1",
      kind: "UserSecret",
      metadata: {},
      spec: { type: Type.DEFAULT },
      status: {},
      data: { type: { oneofKind: "value", value: "" } },
    }),
  );

  const isSSH = req.spec?.type === Type.SSH_KEY;
  const value = req.data?.type.oneofKind === "value" ? req.data.type.value : "";

  const mutation = useMutation({
    mutationFn: async () => {
      const { response } = await client.createUserSecret(req);
      return response;
    },
    onSuccess: () => {
      invalidateUserSecrets();
      toast.success("Secret created");
      navigate("/usersecrets");
    },
    onError,
  });

  return (
    <>
      <Meta title="New User Secret" />
      <PageHeader
        title="New User Secret"
        crumbs={[
          { label: "Your Secrets", to: "/usersecrets" },
          { label: "New" },
        ]}
        description="Personal to you and available in every Workspace you own."
      />

      <div className="max-w-3xl">
        <Stack gap="lg">
          <Panel>
            <PanelHeader
              icon={<IconKey size={16} />}
              title="Identity"
              description="Referenced by this name from your settings and Workspace specs."
            />
            <PanelBody>
              <MetadataEdit
                metadata={req.metadata!}
                parentName={user?.metadata?.name}
                skipDisplayName
                onChange={(md) => {
                  const next = WsPB.UserSecret.clone(req);
                  next.metadata = md;
                  setReq(next);
                }}
              />
            </PanelBody>
          </Panel>

          <Panel>
            <PanelHeader
              icon={<IconLock size={16} />}
              title="Value"
              description="Write-only. You can replace it later but never read it back."
            />
            <PanelBody>
              <Stack gap="lg">
                <div>
                  <Text size="sm" fw={700} mb={2}>
                    Type
                  </Text>
                  <Text size="xs" c="dimmed" mb={8}>
                    An SSH key pair is generated by the Cluster; you get the
                    public half to register with your Git host.
                  </Text>
                  <SegmentedControl
                    value={isSSH ? "ssh" : "default"}
                    onChange={(v) => {
                      const next = WsPB.UserSecret.clone(req);
                      next.spec!.type =
                        v === "ssh" ? Type.SSH_KEY : Type.DEFAULT;
                      next.data!.type = { oneofKind: "value", value: "" };
                      setReq(next);
                    }}
                    data={[
                      { label: "Value", value: "default" },
                      { label: "SSH key", value: "ssh" },
                    ]}
                  />
                </div>

                {isSSH ? (
                  <Alert
                    color="blue"
                    icon={<IconInfoCircle size={16} />}
                    title="Key pair generated for you"
                  >
                    The private key never leaves the Cluster. After creating it,
                    copy the public key from the list and add it to your Git
                    provider.
                  </Alert>
                ) : (
                  <SecretValueInput
                    value={value}
                    onChange={(v) => {
                      const next = WsPB.UserSecret.clone(req);
                      next.data!.type = { oneofKind: "value", value: v };
                      setReq(next);
                    }}
                  />
                )}
              </Stack>
            </PanelBody>
            <PanelFooter>
              <Button variant="default" onClick={() => navigate(-1)}>
                Cancel
              </Button>
              <Button
                loading={mutation.isPending}
                disabled={!req.metadata?.name || (!isSSH && !value)}
                onClick={() => mutation.mutate()}
              >
                Create Secret
              </Button>
            </PanelFooter>
          </Panel>
        </Stack>
      </div>
    </>
  );
};

export default CreateUserSecret;
