import ConfirmAction from "@/components/ConfirmAction";
import Facts, { Fact } from "@/components/Facts";
import MetadataEdit from "@/components/MetadataEdit";
import Panel, { PanelBody, PanelFooter, PanelHeader } from "@/components/Panel";
import SpecEditor from "@/components/SpecEditor";
import { onError } from "@/utils";
import { getClientWorkspace } from "@/utils/client";
import {
  invalidateResource,
  invalidateWorkspaces,
} from "@/utils/octelium";
import { isWorkspaceStopped } from "@/utils/pb";
import { Alert, Button, Stack } from "@mantine/core";
import * as WsPB from "@octelium/apis/main/cordiumv1";
import { DeleteOptions } from "@octelium/apis/main/metav1";
import {
  IconAlertTriangle,
  IconInfoCircle,
  IconTrash,
} from "@tabler/icons-react";
import { useMutation } from "@tanstack/react-query";
import * as React from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import { useContextWorkspace } from "../../utils";

const SettingsForm = (props: { data: WsPB.Workspace }) => {
  const { data } = props;
  const client = getClientWorkspace();
  const navigate = useNavigate();

  const [req, setReq] = React.useState(() => WsPB.Workspace.clone(data));

  const mutationUpdate = useMutation({
    mutationFn: async () => {
      const { response } = await client.updateWorkspace(req!);
      return response;
    },
    onSuccess: (response) => {
      invalidateResource(response);
      invalidateWorkspaces();
      toast.success("Workspace updated");
    },
    onError,
  });

  const mutationDelete = useMutation({
    mutationFn: async () => {
      await client.deleteWorkspace(
        DeleteOptions.create({ uid: data!.metadata!.uid }),
      );
    },
    onSuccess: () => {
      invalidateWorkspaces();
      toast.success("Workspace deleted");
      navigate("/workspaces");
    },
    onError,
  });


  const stopped = isWorkspaceStopped(data);

  return (
    <Stack gap="lg">
      {!stopped && (
        <Alert
          color="blue"
          icon={<IconInfoCircle size={16} />}
          title="Workspace is running"
        >
          Configuration changes are applied the next time this workspace starts.
        </Alert>
      )}

      <Panel>
        <PanelHeader
          title="Identity"
          description="The name is assigned by the Cluster and cannot be changed."
        />
        <PanelBody>
          <MetadataEdit
            metadata={req.metadata!}
            disableName
            withDescription
            nameDescription="Generated by the Cluster when the Workspace was created."
            onChange={(md) => {
              const next = WsPB.Workspace.clone(req);
              next.metadata = md;
              setReq(next);
            }}
          />
        </PanelBody>
      </Panel>

      <Panel>
        <PanelHeader
          title="Configuration"
          description="Overrides the Template this Workspace was created from."
        />
        <PanelBody>
          <SpecEditor
            kind="Workspace"
            item={req}
            spaceRef={data.status!.spaceRef!}
            onChange={(next) => setReq(next as WsPB.Workspace)}
          />
        </PanelBody>
        <PanelFooter>
          <Button
            variant="default"
            onClick={() => setReq(WsPB.Workspace.clone(data))}
          >
            Reset
          </Button>
          <Button
            loading={mutationUpdate.isPending}
            onClick={() => mutationUpdate.mutate()}
          >
            Save changes
          </Button>
        </PanelFooter>
      </Panel>

      <Panel className="border-rose-200">
        <PanelHeader
          icon={<IconAlertTriangle size={16} />}
          title="Danger zone"
          description="Deleting a workspace destroys its persistent storage."
        />
        <PanelBody>
          <ConfirmAction
            triggerLabel="Delete workspace"
            triggerIcon={<IconTrash size={14} />}
            size="sm"
            title="Delete this workspace?"
            confirmLabel="Delete workspace"
            description="Everything inside it, including persistent storage and uncommitted work, is permanently removed."
            details={
              <Facts>
                <Fact label="Name">
                  <span className="font-mono">{data.metadata?.name}</span>
                </Fact>
                <Fact label="UID">
                  <span className="font-mono text-[0.8em]">
                    {data.metadata?.uid}
                  </span>
                </Fact>
              </Facts>
            }
            loading={mutationDelete.isPending}
            onConfirm={() => mutationDelete.mutate()}
          />
        </PanelBody>
      </Panel>
    </Stack>
  );
};

const Page = () => {
  const ctx = useContextWorkspace();
  const data = ctx.workspace.data;

  if (!data) return null;

  return (
    <SettingsForm
      key={`${data.metadata!.uid}:${data.metadata?.updatedAt?.seconds ?? 0}`}
      data={data}
    />
  );
};

export default Page;
