/*
 * Copyright Octelium Labs, LLC. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License version 3,
 * as published by the Free Software Foundation of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: cjoinmanv1.proto

package cjoinmanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{0}
}

type JoinClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// octelium.api.main.core.v1.Region region = 1;
	RegionIndex int32                        `protobuf:"varint,1,opt,name=regionIndex,proto3" json:"regionIndex,omitempty"`
	Storage     *JoinClusterResponse_Storage `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *JoinClusterResponse) Reset() {
	*x = JoinClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse) ProtoMessage() {}

func (x *JoinClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1}
}

func (x *JoinClusterResponse) GetRegionIndex() int32 {
	if x != nil {
		return x.RegionIndex
	}
	return 0
}

func (x *JoinClusterResponse) GetStorage() *JoinClusterResponse_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type JoinClusterResponse_Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primary   *JoinClusterResponse_Storage_Primary   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary *JoinClusterResponse_Storage_Secondary `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
}

func (x *JoinClusterResponse_Storage) Reset() {
	*x = JoinClusterResponse_Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse_Storage) ProtoMessage() {}

func (x *JoinClusterResponse_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse_Storage.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse_Storage) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JoinClusterResponse_Storage) GetPrimary() *JoinClusterResponse_Storage_Primary {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *JoinClusterResponse_Storage) GetSecondary() *JoinClusterResponse_Storage_Secondary {
	if x != nil {
		return x.Secondary
	}
	return nil
}

type JoinClusterResponse_Storage_Primary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*JoinClusterResponse_Storage_Primary_Postgres_
	Type isJoinClusterResponse_Storage_Primary_Type `protobuf_oneof:"type"`
}

func (x *JoinClusterResponse_Storage_Primary) Reset() {
	*x = JoinClusterResponse_Storage_Primary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse_Storage_Primary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse_Storage_Primary) ProtoMessage() {}

func (x *JoinClusterResponse_Storage_Primary) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse_Storage_Primary.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse_Storage_Primary) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (m *JoinClusterResponse_Storage_Primary) GetType() isJoinClusterResponse_Storage_Primary_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *JoinClusterResponse_Storage_Primary) GetPostgres() *JoinClusterResponse_Storage_Primary_Postgres {
	if x, ok := x.GetType().(*JoinClusterResponse_Storage_Primary_Postgres_); ok {
		return x.Postgres
	}
	return nil
}

type isJoinClusterResponse_Storage_Primary_Type interface {
	isJoinClusterResponse_Storage_Primary_Type()
}

type JoinClusterResponse_Storage_Primary_Postgres_ struct {
	Postgres *JoinClusterResponse_Storage_Primary_Postgres `protobuf:"bytes,1,opt,name=postgres,proto3,oneof"`
}

func (*JoinClusterResponse_Storage_Primary_Postgres_) isJoinClusterResponse_Storage_Primary_Type() {}

type JoinClusterResponse_Storage_Secondary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*JoinClusterResponse_Storage_Secondary_Redis_
	Type isJoinClusterResponse_Storage_Secondary_Type `protobuf_oneof:"type"`
}

func (x *JoinClusterResponse_Storage_Secondary) Reset() {
	*x = JoinClusterResponse_Storage_Secondary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse_Storage_Secondary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse_Storage_Secondary) ProtoMessage() {}

func (x *JoinClusterResponse_Storage_Secondary) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse_Storage_Secondary.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse_Storage_Secondary) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (m *JoinClusterResponse_Storage_Secondary) GetType() isJoinClusterResponse_Storage_Secondary_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *JoinClusterResponse_Storage_Secondary) GetRedis() *JoinClusterResponse_Storage_Secondary_Redis {
	if x, ok := x.GetType().(*JoinClusterResponse_Storage_Secondary_Redis_); ok {
		return x.Redis
	}
	return nil
}

type isJoinClusterResponse_Storage_Secondary_Type interface {
	isJoinClusterResponse_Storage_Secondary_Type()
}

type JoinClusterResponse_Storage_Secondary_Redis_ struct {
	Redis *JoinClusterResponse_Storage_Secondary_Redis `protobuf:"bytes,1,opt,name=redis,proto3,oneof"`
}

func (*JoinClusterResponse_Storage_Secondary_Redis_) isJoinClusterResponse_Storage_Secondary_Type() {}

type JoinClusterResponse_Storage_Primary_Postgres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Database string `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port     int32  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	NoSSL    bool   `protobuf:"varint,6,opt,name=noSSL,proto3" json:"noSSL,omitempty"`
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) Reset() {
	*x = JoinClusterResponse_Storage_Primary_Postgres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse_Storage_Primary_Postgres) ProtoMessage() {}

func (x *JoinClusterResponse_Storage_Primary_Postgres) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse_Storage_Primary_Postgres.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse_Storage_Primary_Postgres) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *JoinClusterResponse_Storage_Primary_Postgres) GetNoSSL() bool {
	if x != nil {
		return x.NoSSL
	}
	return false
}

type JoinClusterResponse_Storage_Secondary_Redis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Database int32  `protobuf:"varint,4,opt,name=database,proto3" json:"database,omitempty"`
	Port     int32  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	UseTLS   bool   `protobuf:"varint,6,opt,name=useTLS,proto3" json:"useTLS,omitempty"`
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) Reset() {
	*x = JoinClusterResponse_Storage_Secondary_Redis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjoinmanv1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse_Storage_Secondary_Redis) ProtoMessage() {}

func (x *JoinClusterResponse_Storage_Secondary_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_cjoinmanv1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse_Storage_Secondary_Redis.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse_Storage_Secondary_Redis) Descriptor() ([]byte, []int) {
	return file_cjoinmanv1_proto_rawDescGZIP(), []int{1, 0, 1, 0}
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *JoinClusterResponse_Storage_Secondary_Redis) GetUseTLS() bool {
	if x != nil {
		return x.UseTLS
	}
	return false
}

var File_cjoinmanv1_proto protoreflect.FileDescriptor

var file_cjoinmanv1_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x22, 0x14, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9b, 0x07, 0x0a, 0x13, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x56, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x89, 0x06, 0x0a, 0x07,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x5e, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x07,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x64, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x6f, 0x63, 0x74,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x1a, 0x9d, 0x02,
	0x0a, 0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x6b, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x74, 0x67, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4d, 0x2e, 0x6f, 0x63,
	0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x1a, 0x9c, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x53, 0x53, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x6e, 0x6f, 0x53, 0x53, 0x4c, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x97, 0x02,
	0x0a, 0x09, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x64, 0x0a, 0x05, 0x72,
	0x65, 0x64, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6f, 0x63, 0x74,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x64, 0x69,
	0x73, 0x1a, 0x9b, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x64, 0x69, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x54, 0x4c,
	0x53, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x54, 0x4c, 0x53, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x32, 0x89, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7a, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x33, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x6a, 0x6f,
	0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x6f, 0x63,
	0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6a, 0x6f, 0x69, 0x6e, 0x6d, 0x61,
	0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cjoinmanv1_proto_rawDescOnce sync.Once
	file_cjoinmanv1_proto_rawDescData = file_cjoinmanv1_proto_rawDesc
)

func file_cjoinmanv1_proto_rawDescGZIP() []byte {
	file_cjoinmanv1_proto_rawDescOnce.Do(func() {
		file_cjoinmanv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_cjoinmanv1_proto_rawDescData)
	})
	return file_cjoinmanv1_proto_rawDescData
}

var file_cjoinmanv1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cjoinmanv1_proto_goTypes = []interface{}{
	(*JoinClusterRequest)(nil),                           // 0: octelium.api.cluster.joinman.v1.JoinClusterRequest
	(*JoinClusterResponse)(nil),                          // 1: octelium.api.cluster.joinman.v1.JoinClusterResponse
	(*JoinClusterResponse_Storage)(nil),                  // 2: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage
	(*JoinClusterResponse_Storage_Primary)(nil),          // 3: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Primary
	(*JoinClusterResponse_Storage_Secondary)(nil),        // 4: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Secondary
	(*JoinClusterResponse_Storage_Primary_Postgres)(nil), // 5: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Primary.Postgres
	(*JoinClusterResponse_Storage_Secondary_Redis)(nil),  // 6: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Secondary.Redis
}
var file_cjoinmanv1_proto_depIdxs = []int32{
	2, // 0: octelium.api.cluster.joinman.v1.JoinClusterResponse.storage:type_name -> octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage
	3, // 1: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.primary:type_name -> octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Primary
	4, // 2: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.secondary:type_name -> octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Secondary
	5, // 3: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Primary.postgres:type_name -> octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Primary.Postgres
	6, // 4: octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Secondary.redis:type_name -> octelium.api.cluster.joinman.v1.JoinClusterResponse.Storage.Secondary.Redis
	0, // 5: octelium.api.cluster.joinman.v1.MainService.JoinCluster:input_type -> octelium.api.cluster.joinman.v1.JoinClusterRequest
	1, // 6: octelium.api.cluster.joinman.v1.MainService.JoinCluster:output_type -> octelium.api.cluster.joinman.v1.JoinClusterResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cjoinmanv1_proto_init() }
func file_cjoinmanv1_proto_init() {
	if File_cjoinmanv1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cjoinmanv1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse_Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse_Storage_Primary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse_Storage_Secondary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse_Storage_Primary_Postgres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjoinmanv1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResponse_Storage_Secondary_Redis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cjoinmanv1_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*JoinClusterResponse_Storage_Primary_Postgres_)(nil),
	}
	file_cjoinmanv1_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*JoinClusterResponse_Storage_Secondary_Redis_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cjoinmanv1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cjoinmanv1_proto_goTypes,
		DependencyIndexes: file_cjoinmanv1_proto_depIdxs,
		MessageInfos:      file_cjoinmanv1_proto_msgTypes,
	}.Build()
	File_cjoinmanv1_proto = out.File
	file_cjoinmanv1_proto_rawDesc = nil
	file_cjoinmanv1_proto_goTypes = nil
	file_cjoinmanv1_proto_depIdxs = nil
}
