/*
 * Copyright Octelium Labs, LLC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// Copyright (c) 2020-present Octelium. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3,
// as published by the Free Software Foundation of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ccordiumv1.proto

package ccordiumv1

import (
	context "context"
	cordiumv1 "github.com/octelium/octelium/apis/main/cordiumv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceService_Prepare_FullMethodName       = "/octelium.api.cluster.cordium.v1.WorkspaceService/Prepare"
	WorkspaceService_GetState_FullMethodName      = "/octelium.api.cluster.cordium.v1.WorkspaceService/GetState"
	WorkspaceService_Shutdown_FullMethodName      = "/octelium.api.cluster.cordium.v1.WorkspaceService/Shutdown"
	WorkspaceService_GetGitCreds_FullMethodName   = "/octelium.api.cluster.cordium.v1.WorkspaceService/GetGitCreds"
	WorkspaceService_StoreGitCreds_FullMethodName = "/octelium.api.cluster.cordium.v1.WorkspaceService/StoreGitCreds"
	WorkspaceService_EraseGitCreds_FullMethodName = "/octelium.api.cluster.cordium.v1.WorkspaceService/EraseGitCreds"
	WorkspaceService_ListenEvent_FullMethodName   = "/octelium.api.cluster.cordium.v1.WorkspaceService/ListenEvent"
	WorkspaceService_ListenState_FullMethodName   = "/octelium.api.cluster.cordium.v1.WorkspaceService/ListenState"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceServiceClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetGitCreds(ctx context.Context, in *GetGitCredsRequest, opts ...grpc.CallOption) (*GetGitCredsResponse, error)
	StoreGitCreds(ctx context.Context, in *StoreGitCredsRequest, opts ...grpc.CallOption) (*StoreGitCredsResponse, error)
	EraseGitCreds(ctx context.Context, in *EraseGitCredsRequest, opts ...grpc.CallOption) (*EraseGitCredsResponse, error)
	ListenEvent(ctx context.Context, in *ListenEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenEventResponse], error)
	ListenState(ctx context.Context, in *ListenStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenStateResponse], error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) GetGitCreds(ctx context.Context, in *GetGitCredsRequest, opts ...grpc.CallOption) (*GetGitCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGitCredsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_GetGitCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) StoreGitCreds(ctx context.Context, in *StoreGitCredsRequest, opts ...grpc.CallOption) (*StoreGitCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreGitCredsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_StoreGitCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) EraseGitCreds(ctx context.Context, in *EraseGitCredsRequest, opts ...grpc.CallOption) (*EraseGitCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EraseGitCredsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_EraseGitCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ListenEvent(ctx context.Context, in *ListenEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceService_ServiceDesc.Streams[0], WorkspaceService_ListenEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenEventRequest, ListenEventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_ListenEventClient = grpc.ServerStreamingClient[ListenEventResponse]

func (c *workspaceServiceClient) ListenState(ctx context.Context, in *ListenStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceService_ServiceDesc.Streams[1], WorkspaceService_ListenState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenStateRequest, ListenStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_ListenStateClient = grpc.ServerStreamingClient[ListenStateResponse]

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations must embed UnimplementedWorkspaceServiceServer
// for forward compatibility.
type WorkspaceServiceServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetGitCreds(context.Context, *GetGitCredsRequest) (*GetGitCredsResponse, error)
	StoreGitCreds(context.Context, *StoreGitCredsRequest) (*StoreGitCredsResponse, error)
	EraseGitCreds(context.Context, *EraseGitCredsRequest) (*EraseGitCredsResponse, error)
	ListenEvent(*ListenEventRequest, grpc.ServerStreamingServer[ListenEventResponse]) error
	ListenState(*ListenStateRequest, grpc.ServerStreamingServer[ListenStateResponse]) error
	mustEmbedUnimplementedWorkspaceServiceServer()
}

// UnimplementedWorkspaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceServiceServer struct{}

func (UnimplementedWorkspaceServiceServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedWorkspaceServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedWorkspaceServiceServer) GetGitCreds(context.Context, *GetGitCredsRequest) (*GetGitCredsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitCreds not implemented")
}
func (UnimplementedWorkspaceServiceServer) StoreGitCreds(context.Context, *StoreGitCredsRequest) (*StoreGitCredsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreGitCreds not implemented")
}
func (UnimplementedWorkspaceServiceServer) EraseGitCreds(context.Context, *EraseGitCredsRequest) (*EraseGitCredsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EraseGitCreds not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListenEvent(*ListenEventRequest, grpc.ServerStreamingServer[ListenEventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListenEvent not implemented")
}
func (UnimplementedWorkspaceServiceServer) ListenState(*ListenStateRequest, grpc.ServerStreamingServer[ListenStateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListenState not implemented")
}
func (UnimplementedWorkspaceServiceServer) mustEmbedUnimplementedWorkspaceServiceServer() {}
func (UnimplementedWorkspaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_GetGitCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetGitCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetGitCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetGitCreds(ctx, req.(*GetGitCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_StoreGitCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGitCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).StoreGitCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_StoreGitCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).StoreGitCreds(ctx, req.(*StoreGitCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_EraseGitCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EraseGitCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).EraseGitCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_EraseGitCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).EraseGitCreds(ctx, req.(*EraseGitCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ListenEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceServiceServer).ListenEvent(m, &grpc.GenericServerStream[ListenEventRequest, ListenEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_ListenEventServer = grpc.ServerStreamingServer[ListenEventResponse]

func _WorkspaceService_ListenState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceServiceServer).ListenState(m, &grpc.GenericServerStream[ListenStateRequest, ListenStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_ListenStateServer = grpc.ServerStreamingServer[ListenStateResponse]

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.cluster.cordium.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _WorkspaceService_Prepare_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _WorkspaceService_GetState_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _WorkspaceService_Shutdown_Handler,
		},
		{
			MethodName: "GetGitCreds",
			Handler:    _WorkspaceService_GetGitCreds_Handler,
		},
		{
			MethodName: "StoreGitCreds",
			Handler:    _WorkspaceService_StoreGitCreds_Handler,
		},
		{
			MethodName: "EraseGitCreds",
			Handler:    _WorkspaceService_EraseGitCreds_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenEvent",
			Handler:       _WorkspaceService_ListenEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListenState",
			Handler:       _WorkspaceService_ListenState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ccordiumv1.proto",
}

const (
	WorkspaceSupervisorService_GetState_FullMethodName           = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/GetState"
	WorkspaceSupervisorService_Initialize_FullMethodName         = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/Initialize"
	WorkspaceSupervisorService_Shutdown_FullMethodName           = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/Shutdown"
	WorkspaceSupervisorService_GetTunnelPublicKey_FullMethodName = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/GetTunnelPublicKey"
	WorkspaceSupervisorService_ListenState_FullMethodName        = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/ListenState"
	WorkspaceSupervisorService_ListenEvent_FullMethodName        = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/ListenEvent"
	WorkspaceSupervisorService_GetFailure_FullMethodName         = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/GetFailure"
	WorkspaceSupervisorService_ShutdownAck_FullMethodName        = "/octelium.api.cluster.cordium.v1.WorkspaceSupervisorService/ShutdownAck"
)

// WorkspaceSupervisorServiceClient is the client API for WorkspaceSupervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceSupervisorServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetTunnelPublicKey(ctx context.Context, in *GetTunnelPublicKeyRequest, opts ...grpc.CallOption) (*GetTunnelPublicKeyResponse, error)
	ListenState(ctx context.Context, in *ListenStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenStateResponse], error)
	ListenEvent(ctx context.Context, in *ListenEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenEventResponse], error)
	GetFailure(ctx context.Context, in *GetFailureRequest, opts ...grpc.CallOption) (*GetFailureResponse, error)
	ShutdownAck(ctx context.Context, in *ShutdownAckRequest, opts ...grpc.CallOption) (*ShutdownAckResponse, error)
}

type workspaceSupervisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceSupervisorServiceClient(cc grpc.ClientConnInterface) WorkspaceSupervisorServiceClient {
	return &workspaceSupervisorServiceClient{cc}
}

func (c *workspaceSupervisorServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceSupervisorServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceSupervisorServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceSupervisorServiceClient) GetTunnelPublicKey(ctx context.Context, in *GetTunnelPublicKeyRequest, opts ...grpc.CallOption) (*GetTunnelPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTunnelPublicKeyResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_GetTunnelPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceSupervisorServiceClient) ListenState(ctx context.Context, in *ListenStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceSupervisorService_ServiceDesc.Streams[0], WorkspaceSupervisorService_ListenState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenStateRequest, ListenStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceSupervisorService_ListenStateClient = grpc.ServerStreamingClient[ListenStateResponse]

func (c *workspaceSupervisorServiceClient) ListenEvent(ctx context.Context, in *ListenEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceSupervisorService_ServiceDesc.Streams[1], WorkspaceSupervisorService_ListenEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenEventRequest, ListenEventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceSupervisorService_ListenEventClient = grpc.ServerStreamingClient[ListenEventResponse]

func (c *workspaceSupervisorServiceClient) GetFailure(ctx context.Context, in *GetFailureRequest, opts ...grpc.CallOption) (*GetFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFailureResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_GetFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceSupervisorServiceClient) ShutdownAck(ctx context.Context, in *ShutdownAckRequest, opts ...grpc.CallOption) (*ShutdownAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownAckResponse)
	err := c.cc.Invoke(ctx, WorkspaceSupervisorService_ShutdownAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceSupervisorServiceServer is the server API for WorkspaceSupervisorService service.
// All implementations must embed UnimplementedWorkspaceSupervisorServiceServer
// for forward compatibility.
type WorkspaceSupervisorServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetTunnelPublicKey(context.Context, *GetTunnelPublicKeyRequest) (*GetTunnelPublicKeyResponse, error)
	ListenState(*ListenStateRequest, grpc.ServerStreamingServer[ListenStateResponse]) error
	ListenEvent(*ListenEventRequest, grpc.ServerStreamingServer[ListenEventResponse]) error
	GetFailure(context.Context, *GetFailureRequest) (*GetFailureResponse, error)
	ShutdownAck(context.Context, *ShutdownAckRequest) (*ShutdownAckResponse, error)
	mustEmbedUnimplementedWorkspaceSupervisorServiceServer()
}

// UnimplementedWorkspaceSupervisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceSupervisorServiceServer struct{}

func (UnimplementedWorkspaceSupervisorServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) GetTunnelPublicKey(context.Context, *GetTunnelPublicKeyRequest) (*GetTunnelPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTunnelPublicKey not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) ListenState(*ListenStateRequest, grpc.ServerStreamingServer[ListenStateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListenState not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) ListenEvent(*ListenEventRequest, grpc.ServerStreamingServer[ListenEventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListenEvent not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) GetFailure(context.Context, *GetFailureRequest) (*GetFailureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFailure not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) ShutdownAck(context.Context, *ShutdownAckRequest) (*ShutdownAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownAck not implemented")
}
func (UnimplementedWorkspaceSupervisorServiceServer) mustEmbedUnimplementedWorkspaceSupervisorServiceServer() {
}
func (UnimplementedWorkspaceSupervisorServiceServer) testEmbeddedByValue() {}

// UnsafeWorkspaceSupervisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceSupervisorServiceServer will
// result in compilation errors.
type UnsafeWorkspaceSupervisorServiceServer interface {
	mustEmbedUnimplementedWorkspaceSupervisorServiceServer()
}

func RegisterWorkspaceSupervisorServiceServer(s grpc.ServiceRegistrar, srv WorkspaceSupervisorServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkspaceSupervisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceSupervisorService_ServiceDesc, srv)
}

func _WorkspaceSupervisorService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceSupervisorService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceSupervisorService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceSupervisorService_GetTunnelPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).GetTunnelPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_GetTunnelPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).GetTunnelPublicKey(ctx, req.(*GetTunnelPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceSupervisorService_ListenState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceSupervisorServiceServer).ListenState(m, &grpc.GenericServerStream[ListenStateRequest, ListenStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceSupervisorService_ListenStateServer = grpc.ServerStreamingServer[ListenStateResponse]

func _WorkspaceSupervisorService_ListenEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceSupervisorServiceServer).ListenEvent(m, &grpc.GenericServerStream[ListenEventRequest, ListenEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceSupervisorService_ListenEventServer = grpc.ServerStreamingServer[ListenEventResponse]

func _WorkspaceSupervisorService_GetFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).GetFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_GetFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).GetFailure(ctx, req.(*GetFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceSupervisorService_ShutdownAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceSupervisorServiceServer).ShutdownAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceSupervisorService_ShutdownAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceSupervisorServiceServer).ShutdownAck(ctx, req.(*ShutdownAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceSupervisorService_ServiceDesc is the grpc.ServiceDesc for WorkspaceSupervisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceSupervisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.cluster.cordium.v1.WorkspaceSupervisorService",
	HandlerType: (*WorkspaceSupervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _WorkspaceSupervisorService_GetState_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _WorkspaceSupervisorService_Initialize_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _WorkspaceSupervisorService_Shutdown_Handler,
		},
		{
			MethodName: "GetTunnelPublicKey",
			Handler:    _WorkspaceSupervisorService_GetTunnelPublicKey_Handler,
		},
		{
			MethodName: "GetFailure",
			Handler:    _WorkspaceSupervisorService_GetFailure_Handler,
		},
		{
			MethodName: "ShutdownAck",
			Handler:    _WorkspaceSupervisorService_ShutdownAck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenState",
			Handler:       _WorkspaceSupervisorService_ListenState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListenEvent",
			Handler:       _WorkspaceSupervisorService_ListenEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ccordiumv1.proto",
}

const (
	TerminalService_CreateTerminal_FullMethodName    = "/octelium.api.cluster.cordium.v1.TerminalService/CreateTerminal"
	TerminalService_RemoveTerminal_FullMethodName    = "/octelium.api.cluster.cordium.v1.TerminalService/RemoveTerminal"
	TerminalService_ListTerminal_FullMethodName      = "/octelium.api.cluster.cordium.v1.TerminalService/ListTerminal"
	TerminalService_WriteDataTerminal_FullMethodName = "/octelium.api.cluster.cordium.v1.TerminalService/WriteDataTerminal"
	TerminalService_SetWindowSize_FullMethodName     = "/octelium.api.cluster.cordium.v1.TerminalService/SetWindowSize"
	TerminalService_ListenTerminal_FullMethodName    = "/octelium.api.cluster.cordium.v1.TerminalService/ListenTerminal"
	TerminalService_Exec_FullMethodName              = "/octelium.api.cluster.cordium.v1.TerminalService/Exec"
)

// TerminalServiceClient is the client API for TerminalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TerminalServiceClient interface {
	CreateTerminal(ctx context.Context, in *CreateTerminalRequest, opts ...grpc.CallOption) (*CreateTerminalResponse, error)
	RemoveTerminal(ctx context.Context, in *RemoveTerminalRequest, opts ...grpc.CallOption) (*RemoveTerminalResponse, error)
	ListTerminal(ctx context.Context, in *ListTerminalRequest, opts ...grpc.CallOption) (*ListTerminalResponse, error)
	WriteDataTerminal(ctx context.Context, in *WriteDataTerminalRequest, opts ...grpc.CallOption) (*WriteDataTerminalResponse, error)
	SetWindowSize(ctx context.Context, in *SetWindowSizeRequest, opts ...grpc.CallOption) (*SetWindowSizeResponse, error)
	ListenTerminal(ctx context.Context, in *ListenTerminalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenTerminalResponse], error)
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[cordiumv1.ExecRequest, cordiumv1.ExecResponse], error)
}

type terminalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalServiceClient(cc grpc.ClientConnInterface) TerminalServiceClient {
	return &terminalServiceClient{cc}
}

func (c *terminalServiceClient) CreateTerminal(ctx context.Context, in *CreateTerminalRequest, opts ...grpc.CallOption) (*CreateTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_CreateTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) RemoveTerminal(ctx context.Context, in *RemoveTerminalRequest, opts ...grpc.CallOption) (*RemoveTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_RemoveTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) ListTerminal(ctx context.Context, in *ListTerminalRequest, opts ...grpc.CallOption) (*ListTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_ListTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) WriteDataTerminal(ctx context.Context, in *WriteDataTerminalRequest, opts ...grpc.CallOption) (*WriteDataTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDataTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_WriteDataTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) SetWindowSize(ctx context.Context, in *SetWindowSizeRequest, opts ...grpc.CallOption) (*SetWindowSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWindowSizeResponse)
	err := c.cc.Invoke(ctx, TerminalService_SetWindowSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) ListenTerminal(ctx context.Context, in *ListenTerminalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenTerminalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TerminalService_ServiceDesc.Streams[0], TerminalService_ListenTerminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenTerminalRequest, ListenTerminalResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_ListenTerminalClient = grpc.ServerStreamingClient[ListenTerminalResponse]

func (c *terminalServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[cordiumv1.ExecRequest, cordiumv1.ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TerminalService_ServiceDesc.Streams[1], TerminalService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[cordiumv1.ExecRequest, cordiumv1.ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_ExecClient = grpc.BidiStreamingClient[cordiumv1.ExecRequest, cordiumv1.ExecResponse]

// TerminalServiceServer is the server API for TerminalService service.
// All implementations must embed UnimplementedTerminalServiceServer
// for forward compatibility.
type TerminalServiceServer interface {
	CreateTerminal(context.Context, *CreateTerminalRequest) (*CreateTerminalResponse, error)
	RemoveTerminal(context.Context, *RemoveTerminalRequest) (*RemoveTerminalResponse, error)
	ListTerminal(context.Context, *ListTerminalRequest) (*ListTerminalResponse, error)
	WriteDataTerminal(context.Context, *WriteDataTerminalRequest) (*WriteDataTerminalResponse, error)
	SetWindowSize(context.Context, *SetWindowSizeRequest) (*SetWindowSizeResponse, error)
	ListenTerminal(*ListenTerminalRequest, grpc.ServerStreamingServer[ListenTerminalResponse]) error
	Exec(grpc.BidiStreamingServer[cordiumv1.ExecRequest, cordiumv1.ExecResponse]) error
	mustEmbedUnimplementedTerminalServiceServer()
}

// UnimplementedTerminalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerminalServiceServer struct{}

func (UnimplementedTerminalServiceServer) CreateTerminal(context.Context, *CreateTerminalRequest) (*CreateTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) RemoveTerminal(context.Context, *RemoveTerminalRequest) (*RemoveTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) ListTerminal(context.Context, *ListTerminalRequest) (*ListTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) WriteDataTerminal(context.Context, *WriteDataTerminalRequest) (*WriteDataTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteDataTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) SetWindowSize(context.Context, *SetWindowSizeRequest) (*SetWindowSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWindowSize not implemented")
}
func (UnimplementedTerminalServiceServer) ListenTerminal(*ListenTerminalRequest, grpc.ServerStreamingServer[ListenTerminalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListenTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) Exec(grpc.BidiStreamingServer[cordiumv1.ExecRequest, cordiumv1.ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedTerminalServiceServer) mustEmbedUnimplementedTerminalServiceServer() {}
func (UnimplementedTerminalServiceServer) testEmbeddedByValue()                         {}

// UnsafeTerminalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminalServiceServer will
// result in compilation errors.
type UnsafeTerminalServiceServer interface {
	mustEmbedUnimplementedTerminalServiceServer()
}

func RegisterTerminalServiceServer(s grpc.ServiceRegistrar, srv TerminalServiceServer) {
	// If the following call pancis, it indicates UnimplementedTerminalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerminalService_ServiceDesc, srv)
}

func _TerminalService_CreateTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).CreateTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_CreateTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).CreateTerminal(ctx, req.(*CreateTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_RemoveTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).RemoveTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_RemoveTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).RemoveTerminal(ctx, req.(*RemoveTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_ListTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).ListTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_ListTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).ListTerminal(ctx, req.(*ListTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_WriteDataTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteDataTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).WriteDataTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_WriteDataTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).WriteDataTerminal(ctx, req.(*WriteDataTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_SetWindowSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWindowSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).SetWindowSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_SetWindowSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).SetWindowSize(ctx, req.(*SetWindowSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_ListenTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenTerminalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TerminalServiceServer).ListenTerminal(m, &grpc.GenericServerStream[ListenTerminalRequest, ListenTerminalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_ListenTerminalServer = grpc.ServerStreamingServer[ListenTerminalResponse]

func _TerminalService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TerminalServiceServer).Exec(&grpc.GenericServerStream[cordiumv1.ExecRequest, cordiumv1.ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TerminalService_ExecServer = grpc.BidiStreamingServer[cordiumv1.ExecRequest, cordiumv1.ExecResponse]

// TerminalService_ServiceDesc is the grpc.ServiceDesc for TerminalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.cluster.cordium.v1.TerminalService",
	HandlerType: (*TerminalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTerminal",
			Handler:    _TerminalService_CreateTerminal_Handler,
		},
		{
			MethodName: "RemoveTerminal",
			Handler:    _TerminalService_RemoveTerminal_Handler,
		},
		{
			MethodName: "ListTerminal",
			Handler:    _TerminalService_ListTerminal_Handler,
		},
		{
			MethodName: "WriteDataTerminal",
			Handler:    _TerminalService_WriteDataTerminal_Handler,
		},
		{
			MethodName: "SetWindowSize",
			Handler:    _TerminalService_SetWindowSize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenTerminal",
			Handler:       _TerminalService_ListenTerminal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _TerminalService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ccordiumv1.proto",
}
